duolingo_set_0 = {
    'name' : 'Duolingo Set 0',
    'words' : [
        (("the collection"), ("die Sammlung")),
        (("international"), ("international")),
        (("own"), ("eigenes")),
        (("public"), ("öffentliche")),
        (("also"), ("auch")),
        (("because"), ("denn")),
        (("I"), ("ich")),
        (("just"), ("nur")),
        (("she"), ("sie")),
        (("active"), ("aktiv")),
        (("him"), ("ihn")),
        (("now"), ("jetzt")),
        (("for"), ("für")),
        (("my"), ("mein")),
        (("and"), ("und")),
        (("bad"), ("schlecht")),
        (("personally"), ("persönlich")),
        (("not"), ("nicht")),
        (("very"), ("sehr")),
        (("value"), ("wert")),
        (("rather"), ("sondern")),
        (("great"), ("toll")),
        (("ready"), ("bereit")),
        (("her"), ("ihr")),
        (("own"), ("eigener")),
        (("v. dances"), ("tanzt")),
        (("excellent"), ("ausgezeichnet")),
        (("always"), ("immer")),
        (("short"), ("kurz")),
        (("with pleasure"), ("gerne")),
    ]
}
duolingo_set_1 = {
    'name' : 'Duolingo Set 1',
    'words' : [
        (("indeed"), ("tatsächlich")),
        (("own"), ("eigene")),
        (("two"), ("zwei")),
        (("four"), ("vier")),
        (("today"), ("heute")),
        (("you"), ("du")),
        (("it"), ("es")),
        (("sometimes"), ("manchmal")),
        (("the children"), ("die Kinder")),
        (("there"), ("dort")),
        (("above"), ("oben")),
        (("excited"), ("begeistert")),
        (("real"), ("echt")),
        (("open"), ("offene")),
        (("popular"), ("beliebt")),
        (("yours"), ("deine")),
        (("where"), ("wo")),
        (("green"), ("grün")),
        (("we"), ("wir")),
        (("he"), ("er")),
        (("sweet"), ("süß")),
        (("interesting"), ("interessant")),
        (("expensive"), ("teuer")),
        (("rich"), ("reich")),
        (("the movie"), ("der Film")),
        (("the movies"), ("die Filme")),
        (("the models"), ("die Modelle")),
        (("the begin"), ("der Start")),
        (("five"), ("fünf")),
        (("the instrument"), ("das Instrument")),
    ]
}
duolingo_set_2 = {
    'name' : 'Duolingo Set 2',
    'words' : [
        (("the artists"), ("die Künstler")),
        (("the theatre"), ("das Theater")),
        (("in any case"), ("jedenfalls")),
        (("even though"), ("obwohl")),
        (("the exhibition"), ("die Ausstellung")),
        (("the guitar"), ("die Gitarre")),
        (("the arts"), ("die Künste")),
        (("him"), ("ihm")),
        (("out"), ("aus")),
        (("with"), ("mit")),
        (("to you"), ("dir")),
        (("us"), ("uns")),
        (("never"), ("nie")),
        (("me"), ("mir")),
        (("my"), ("meine")),
        (("yes"), ("ja")),
        (("beautiful"), ("schon")),
        (("that"), ("dass")),
        (("me"), ("mich")),
        (("three"), ("drei")),
        (("so"), ("so")),
        (("ever"), ("je")),
        (("happens"), ("passiert")),
        (("i agree"), ("genau")),
        (("as"), ("wie")),
        (("on it"), ("daran")),
        (("yesterday"), ("gestern")),
        (("you"), ("dich")),
        (("responsible"), ("zuständig")),
        (("clear"), ("klar")),
    ]
}
duolingo_set_3 = {
    'name' : 'Duolingo Set 3',
    'words' : [
        (("more"), ("mehr")),
        (("often"), ("oft")),
        (("slowly"), ("langsam")),
        (("funny"), ("komisch")),
        (("back"), ("zurück")),
        (("path"), ("weg")),
        (("in order to"), ("damit")),
        (("free"), ("kostenlos")),
        (("completely"), ("komplett")),
        (("clearly"), ("eindeutig")),
        (("complete"), ("komplette")),
        (("at"), ("bei")),
        (("round"), ("rund")),
        (("tomorrow"), ("morgen")),
        (("onto"), ("aufs")),
        (("probably"), ("wahrscheinlich")),
        (("necessary"), ("notwendig")),
        (("later"), ("später")),
        (("none"), ("keinen")),
        (("but"), ("aber")),
        (("long"), ("lange")),
        (("then"), ("dann")),
        (("after"), ("nach")),
        (("to"), ("zu")),
        (("satisfied"), ("zufrieden")),
        (("something"), ("etwas")),
        (("as long as"), ("solange")),
        (("no way"), ("niemals")),
        (("the player"), ("der Spieler")),
        (("welcome"), ("willkommen")),
    ]
}
duolingo_set_4 = {
    'name' : 'Duolingo Set 4',
    'words' : [
        (("big"), ("groß")),
        (("strong"), ("stark")),
        (("healthy"), ("gesund")),
        (("with it"), ("dabei")),
        (("fast"), ("schnell")),
        (("to"), ("zu")),
        (("the woman"), ("die Frau")),
        (("kind"), ("nett")),
        (("small"), ("klein")),
        (("or"), ("oder")),
        (("the men"), ("die Männer")),
        (("a lot of"), ("viel")),
        (("late"), ("spät")),
        (("together"), ("zusammen")),
        (("you're welcome"), ("bitte")),
        (("the milk"), ("die Milch")),
        (("the game"), ("das Spiel")),
        (("again"), ("wieder")),
        (("there"), ("da")),
        (("no one"), ("niemand")),
        (("the newspaper"), ("die Zeitung")),
        (("so far"), ("bisher")),
        (("salty"), ("salzig")),
        (("v. have"), ("habe")),
        (("the soccer"), ("fußball Fußball")),
        (("calm"), ("ruhig")),
        (("the german"), ("das Deutsch")),
        (("more"), ("mehr")),
        (("seven"), ("sieben")),
        (("scarce"), ("knapp")),
    ]
}
duolingo_set_5 = {
    'name' : 'Duolingo Set 5',
    'words' : [
        (("broken"), ("kaputt")),
        (("outside"), ("draußen")),
        (("when"), ("als")),
        (("about that"), ("darüber")),
        (("right away"), ("sofort")),
        (("for this"), ("dafür")),
        (("to you"), ("euch")),
        (("here"), ("hier")),
        (("now"), ("nun")),
        (("that's why"), ("deshalb")),
        (("after that"), ("danach")),
        (("still"), ("noch")),
        (("when"), ("wann")),
        (("from that"), ("davon")),
        (("easy"), ("einfach")),
        (("stronger"), ("stärker")),
        (("smaller"), ("kleiner")),
        (("the hunger"), ("der Hunger")),
        (("the boys"), ("die Jungen")),
        (("blue"), ("blau")),
        (("the boy"), ("der Junge")),
        (("at the"), ("am")),
        (("the loaf"), ("das Brot")),
        (("the ducks"), ("die Enten")),
        (("right"), ("rechts")),
        (("new"), ("neu")),
        (("left"), ("links")),
        (("cheap"), ("billig")),
        (("if"), ("wenn")),
        (("no"), ("nein")),
    ]
}
duolingo_set_6 = {
    'name' : 'Duolingo Set 6',
    'words' : [
        (("of"), ("von")),
        (("soon"), ("bald")),
        (("different"), ("verschiedenen")),
        (("well"), ("gut")),
        (("higher"), ("höher")),
        (("v. to have"), ("haben")),
        (("better"), ("besser")),
        (("but"), ("doch")),
        (("important"), ("wichtig")),
        (("free"), ("gratis")),
        (("therefore"), ("darum")),
        (("good"), ("guten")),
        (("as"), ("wie")),
        (("good"), ("guten")),
        (("similar"), ("ähnlich")),
        (("heavy"), ("schwer")),
        (("your"), ("dein")),
        (("early"), ("früh")),
        (("by which"), ("womit")),
        (("for what"), ("wofür")),
        (("the man"), ("der Mann")),
        (("about what"), ("worüber")),
        (("v. are"), ("seid")),
        (("how so"), ("wieso")),
        (("the child"), ("das Kind")),
        (("beautiful"), ("schön")),
        (("high"), ("hoch")),
        (("the branch"), ("die Branche")),
        (("the service"), ("der Dienstleistung")),
        (("full"), ("voll")),
    ]
}
duolingo_set_7 = {
    'name' : 'Duolingo Set 7',
    'words' : [
        (("the assignment"), ("die Auftrag")),
        (("regional"), ("regional")),
        (("the request"), ("die Antrag")),
        (("the documentation"), ("die Dokumentation")),
        (("the activity"), ("die Tätigkeit")),
        (("the camera"), ("die Kamera")),
        (("the actor"), ("der Schauspieler")),
        (("the movie theater"), ("der Kino")),
        (("black"), ("schwarz")),
        (("the concerts"), ("die Konzerte")),
        (("the concert"), ("das Konzert")),
        (("the dance"), ("der Tanz")),
        (("the frame"), ("der Rahmen")),
        (("the style"), ("der Stil")),
        (("the stage"), ("die Bühne")),
        (("the fashion"), ("die Mode")),
        (("front"), ("vorne")),
        (("available"), ("verfügbar")),
        (("the literature"), ("die Literatur")),
        (("the museum"), ("das Museum")),
        (("the design"), ("das Design")),
        (("the criticism"), ("die Kritik")),
        (("the song"), ("das Lied")),
        (("the photography"), ("die Fotografie")),
        (("the draft"), ("der Entwurf")),
        (("the model"), ("das Modell")),
        (("the instruments"), ("die Instrumente")),
        (("the culture"), ("die Kultur")),
        (("the music"), ("die Musik")),
        (("the gallery"), ("die Galerie")),
    ]
}
duolingo_set_8 = {
    'name' : 'Duolingo Set 8',
    'words' : [
        (("the exhibitions"), ("die Ausstellungen")),
        (("the art"), ("die Kunst")),
        (("the musician"), ("der Musiker")),
        (("the studio"), ("das Studio")),
        (("without"), ("ohne")),
        (("yellow"), ("gelb")),
        (("usually"), ("gewöhnlich")),
        (("free"), ("frei")),
        (("pink"), ("pink")),
        (("eight"), ("acht")),
        (("gladly"), ("gern")),
        (("ten"), ("zehn")),
        (("six"), ("sechs")),
        (("nine"), ("neun")),
        (("one"), ("eins")),
        (("v. snowing"), ("schneit")),
        (("v. raining"), ("regnet")),
        (("warm"), ("warm")),
        (("rare"), ("selten")),
        (("practically"), ("praktisch")),
        (("right one"), ("richtige")),
        (("clear"), ("deutlich")),
        (("versus"), ("gegen")),
        (("old"), ("alt")),
        (("possible"), ("möglich")),
        (("pregnant"), ("schwanger")),
        (("married"), ("verheiratet")),
        (("higher"), ("höhere")),
        (("already"), ("bereits")),
        (("useful"), ("nützlich")),
    ]
}
duolingo_set_9 = {
    'name' : 'Duolingo Set 9',
    'words' : [
        (("once"), ("einmal")),
        (("the movements"), ("die Bewegungen")),
        (("the swimming pool"), ("das Schwimmbad")),
        (("the bet"), ("die Wette")),
        (("the leisure"), ("die Freizeit")),
        (("the ski"), ("der Ski")),
        (("the move"), ("die Bewegung")),
        (("my"), ("meinem")),
        (("the team"), ("die Mannschaft")),
        (("the victory"), ("der Sieg")),
        (("the spectator"), ("der Zuschauer")),
        (("the league"), ("die Liga")),
        (("the participation"), ("die Teilnahme")),
        (("the games"), ("die Spiele")),
        (("the team"), ("die Team")),
        (("the sports"), ("der Sport")),
        (("the hobby"), ("das Hobby")),
        (("the ball"), ("der Ball")),
        (("the activities"), ("die Aktivitäten")),
        (("v. negotiate"), ("verhandeln")),
        (("the business"), ("das Betrieb")),
        (("the industry sectors"), ("die Branchen")),
        (("the companies"), ("die Betriebe")),
        (("the services"), ("die Dienstleistungen")),
        (("the requirement"), ("die Bedarf")),
        (("the services"), ("die Leistungen")),
        (("the expenditure"), ("die Ausgaben")),
        (("the stock exchange"), ("die Börse")),
        (("the founding"), ("die Gründung")),
        (("the production"), ("die Produktion")),
    ]
}
duolingo_set_10 = {
    'name' : 'Duolingo Set 10',
    'words' : [
        (("the rating"), ("das Bewertung")),
        (("the service"), ("der Service")),
        (("the advertising"), ("die Werbung")),
        (("the pay"), ("die Bezahlung")),
        (("the brand"), ("die Marke")),
        (("the warehouse"), ("das Lager")),
        (("the opportunities"), ("die Chancen")),
        (("the deals"), ("die Angebote")),
        (("the fair"), ("der Messe")),
        (("the chance"), ("die Chance")),
        (("the display"), ("der Anzeige")),
        (("the offer"), ("das Angebot")),
        (("the guarantee"), ("die Garantie")),
        (("the tables"), ("die Tabellen")),
        (("the sale"), ("der Verkauf")),
        (("the delivery"), ("die Lieferung")),
        (("the would"), ("das Ware")),
        (("the industry"), ("die Industrie")),
        (("the company"), ("die Firma")),
        (("the insurance"), ("die Versicherung")),
        (("young"), ("jung")),
        (("yours"), ("deinen")),
        (("the use"), ("die Gebrauch")),
        (("same"), ("gleiche")),
        (("before"), ("zuvor")),
        (("precious"), ("wertvoll")),
        (("different"), ("anders")),
        (("last"), ("letzter")),
        (("personal"), ("persönlichen")),
        (("perfect"), ("perfekt")),
    ]
}
duolingo_set_11 = {
    'name' : 'Duolingo Set 11',
    'words' : [
        (("all"), ("ganz")),
        (("for real"), ("wirklich")),
        (("positive"), ("positiv")),
        (("red"), ("rot")),
        (("the judges"), ("die Richterinnen")),
        (("the child"), ("das Kindes")),
        (("hot"), ("heiß")),
        (("open"), ("offen")),
        (("white"), ("weiß")),
        (("to the"), ("zum")),
        (("light"), ("leicht")),
        (("gladly"), ("gern")),
        (("the implementation"), ("die Umsetzung")),
        (("the combination"), ("die Kombination")),
        (("the status"), ("der Zustand")),
        (("the commitment"), ("die Einsatz")),
        (("the circle"), ("der Kreis")),
        (("unknown"), ("unbekannt")),
        (("the party"), ("die Party")),
        (("the field"), ("das Feld")),
        (("the details"), ("die Einzelheiten")),
        (("the parties"), ("die Parties")),
        (("the weight"), ("das Gewicht")),
        (("pair"), ("paar")),
        (("to"), ("bis")),
        (("the course"), ("der Verlauf")),
        (("the manual"), ("das Anleitung")),
        (("long"), ("langen")),
        (("yearly"), ("jährlich")),
        (("the average"), ("der Mitteln")),
    ]
}
duolingo_set_12 = {
    'name' : 'Duolingo Set 12',
    'words' : [
        (("the proposals"), ("die Vorschläge")),
        (("the suggestion"), ("der Vorschlag")),
        (("the categories"), ("die Kategorien")),
        (("the quantity"), ("die Menge")),
        (("the list"), ("die Liste")),
        (("the difference"), ("der Unterschied")),
        (("the regulations"), ("die Bestimmungen")),
        (("the experience"), ("die Erfahrungen")),
        (("the versions"), ("die Versionen")),
        (("the look"), ("der Blick")),
        (("the overview"), ("der Überblick")),
        (("the fields"), ("die Felder")),
        (("the credentials"), ("die Referenzen")),
        (("the parties"), ("die Partys")),
        (("the effect"), ("der Wirkung")),
        (("the step"), ("der Stufe")),
        (("by"), ("durch")),
        (("the role"), ("die Rolle")),
        (("the background"), ("der Hintergrund")),
        (("the column"), ("die Spalte")),
        (("the use"), ("die Verwendung")),
        (("the introduction"), ("die Einführung")),
        (("the position"), ("die Position")),
        (("the access"), ("der Zugang")),
        (("the medium"), ("das Mittel")),
        (("the height"), ("die Höhe")),
        (("the length"), ("die Länge")),
        (("the force"), ("die Kraft")),
        (("the category"), ("die Kategorie")),
        (("the characteristics"), ("die Eigenschaften")),
    ]
}
duolingo_set_13 = {
    'name' : 'Duolingo Set 13',
    'words' : [
        (("the support"), ("die Unterstützung")),
        (("the original"), ("das Original")),
        (("long"), ("lang")),
        (("the version"), ("die Version")),
        (("the improvement"), ("die Verbesserung")),
        (("the determination"), ("die Bestimmung")),
        (("the differences"), ("die Unterschiede")),
        (("the planning"), ("die Planung")),
        (("the experience"), ("die Erfahrung")),
        (("wonderful"), ("wunderbar")),
        (("according to"), ("laut")),
        (("from where"), ("woher")),
        (("past"), ("vorbei")),
        (("equal"), ("gleich")),
        (("plus"), ("plus")),
        (("responsible"), ("verantwortlich")),
        (("minus"), ("minus")),
        (("entire"), ("gesamte")),
        (("naturally"), ("natürlich")),
        (("higher"), ("hoher")),
        (("especially"), ("besonders")),
        (("the account"), ("das Konto")),
        (("the coin"), ("die Münze")),
        (("the interest"), ("die Zinsen")),
        (("the coins"), ("die Münzen")),
        (("the payment"), ("die Zahlung")),
        (("correct"), ("richtig")),
        (("individual"), ("einzelnen")),
        (("equal"), ("gleich")),
        (("the financing"), ("die Finanzierung")),
    ]
}
duolingo_set_14 = {
    'name' : 'Duolingo Set 14',
    'words' : [
        (("the deadline"), ("die Frist")),
        (("delicious"), ("lecker")),
        (("cold"), ("kalt")),
        (("the amount"), ("die Betrag")),
        (("the bill"), ("die Rechnung")),
        (("if"), ("falls")),
        (("little"), ("bisschen")),
        (("even"), ("selbst")),
        (("as soon as"), ("sobald")),
        (("alone"), ("alleine")),
        (("long"), ("lange")),
        (("fewer"), ("weniger")),
        (("times"), ("mal")),
        (("thereon"), ("darauf")),
        (("himself"), ("selber")),
        (("why"), ("warum")),
        (("private"), ("privat")),
        (("purely"), ("rein")),
        (("alone"), ("allein")),
        (("v. would be"), ("wären")),
        (("v. would have"), ("hätten")),
        (("thin"), ("dünn")),
        (("maybe"), ("vielleicht")),
        (("beautiful"), ("wunderschön")),
        (("to"), ("zur")),
        (("the ghost"), ("das Geist")),
        (("at least"), ("mindestens")),
        (("invisible"), ("unsichtbar")),
        (("there"), ("da")),
        (("the emotions"), ("die Gefühlen")),
    ]
}
duolingo_set_15 = {
    'name' : 'Duolingo Set 15',
    'words' : [
        (("the life"), ("das Lebens")),
        (("the senses"), ("die Sinne")),
        (("the soul"), ("die Seele")),
        (("the life"), ("das Leben")),
        (("new"), ("neue")),
        (("the hope"), ("die Hoffnung")),
        (("v. meditate"), ("meditiere")),
        (("the fate"), ("das Schicksal")),
        (("the truth"), ("die Wahrheit")),
        (("the balance"), ("die Gleichgewicht")),
        (("the feeling"), ("das Gefühl")),
        (("the sense"), ("der Sinn")),
        (("the souls"), ("die Seelen")),
        (("the wonder"), ("das Wunder")),
        (("the spirituality"), ("die Spiritualität")),
        (("every day"), ("täglich")),
        (("suitable"), ("passende")),
        (("entire"), ("gesamten")),
        (("special"), ("speziellen")),
        (("past"), ("vergangenen")),
        (("additional"), ("weiteres")),
        (("all over"), ("überall")),
        (("the english"), ("das Englisch")),
        (("honest"), ("ehrlich")),
        (("even"), ("sogar")),
        (("next"), ("nächsten")),
        (("furthermore"), ("außerdem")),
        (("at all"), ("gar")),
        (("bad"), ("schlimm")),
        (("empty"), ("leer")),
    ]
}
duolingo_set_16 = {
    'name' : 'Duolingo Set 16',
    'words' : [
        (("v. eat"), ("essen")),
        (("thick"), ("dick")),
        (("lovely"), ("schöne")),
        (("here"), ("her")),
        (("around"), ("herum")),
        (("out"), ("hinaus")),
        (("down"), ("hin")),
        (("ahead"), ("voraus")),
        (("from"), ("vom")),
        (("here"), ("hierher")),
        (("the thigh"), ("die Oberschenkel")),
        (("the muscles"), ("die Muskeln")),
        (("the bowel"), ("der Darm")),
        (("the organ"), ("das Organ")),
        (("weak"), ("schwach")),
        (("finally"), ("endlich")),
        (("so far"), ("soweit")),
        (("interesting"), ("interessante")),
        (("the elbow"), ("der Ellbogen")),
        (("the heel"), ("die Ferse")),
        (("the bellies"), ("die Bäuche")),
        (("the forehead"), ("die Stirn")),
        (("the brain"), ("das Gehirn")),
        (("the lungs"), ("die Lungen")),
        (("usually"), ("normalerweise")),
        (("the muscle"), ("der Muskel")),
        (("the bone"), ("der Knochen")),
        (("the intestines"), ("der Därme")),
        (("the liver"), ("die Leber")),
        (("the organs"), ("die Organe")),
    ]
}
duolingo_set_17 = {
    'name' : 'Duolingo Set 17',
    'words' : [
        (("the hips"), ("die Hüften")),
        (("the toes"), ("die Zehen")),
        (("the hip"), ("die Hüfte")),
        (("the toe"), ("der Zeh")),
        (("the heels"), ("die Fersen")),
        (("the knee"), ("das Knie")),
        (("the belly"), ("der Bauch")),
        (("the thumb"), ("der Daumen")),
        (("the lip"), ("die Lippe")),
        (("the brains"), ("die Gehirnen")),
        (("the lung"), ("die Lunge")),
        (("the chin"), ("das Kinn")),
        (("thanks"), ("danke")),
        (("bye"), ("tschüss")),
        (("hi there"), ("hallo")),
        (("again"), ("erneut")),
        (("lighter"), ("leichter")),
        (("weekly"), ("wöchentlich")),
        (("helpful"), ("hilfreich")),
        (("because"), ("weil")),
        (("before"), ("bevor")),
        (("thereby"), ("dadurch")),
        (("per month"), ("monatlich")),
        (("today"), ("heutigen")),
        (("common"), ("gemeinsame")),
        (("former"), ("ehemaligen")),
        (("own"), ("eigenen")),
        (("matching"), ("passenden")),
        (("higher"), ("höheren")),
        (("dry"), ("trocken")),
    ]
}
duolingo_set_18 = {
    'name' : 'Duolingo Set 18',
    'words' : [
        (("out"), ("raus")),
        (("meanwhile"), ("inzwischen")),
        (("v. increase"), ("erhöhen")),
        (("v. acquire"), ("erwerben")),
        (("mean"), ("meinen")),
        (("v. burn"), ("brennen")),
        (("v. kick"), ("trete")),
        (("v. will"), ("werde")),
        (("v. occurs"), ("tritt")),
        (("v. right"), ("stimmt")),
        (("v. voice"), ("stimme")),
        (("tired"), ("müde")),
        (("v. developed"), ("entwickelt")),
        (("v. avoid"), ("vermeiden")),
        (("v. to calculate"), ("berechnen")),
        (("v. acquires"), ("erwirbt")),
        (("v. enable"), ("ermöglichen")),
        (("v. appear"), ("erscheinen")),
        (("v. determine"), ("ermitteln")),
        (("v. receive"), ("erhalten")),
        (("v. reached"), ("erreicht")),
        (("v. does"), ("tut")),
        (("v. earned"), ("verdient")),
        (("v. support"), ("unterstütze")),
        (("v. turn"), ("wenden")),
        (("v. to do"), ("tun")),
        (("v. respect, think highly of"), ("achten")),
        (("v. switch"), ("wechseln")),
        (("v. to earn"), ("verdienen")),
        (("if"), ("ob")),
    ]
}
duolingo_set_19 = {
    'name' : 'Duolingo Set 19',
    'words' : [
        (("v. define"), ("definieren")),
        (("v. quote"), ("zitieren")),
        (("v. marked"), ("markiert")),
        (("v. present"), ("präsentieren")),
        (("v. presents"), ("präsentiert")),
        (("v. to mark"), ("markieren")),
        (("v. talk"), ("reden")),
        (("v. you're welcome"), ("bitte")),
        (("v. speech"), ("rede")),
        (("v. reports"), ("meldet")),
        (("v. call"), ("nennen")),
        (("v. jumps"), ("springt")),
        (("v. becomes"), ("wird")),
        (("v. to step"), ("treten")),
        (("v. be right"), ("stimmen")),
        (("v. divide"), ("teilen")),
        (("v. use"), ("nutzen")),
        (("v. share"), ("teile")),
        (("v. promote"), ("fördern")),
        (("v. to forget"), ("vergessen")),
        (("v. to compare"), ("vergleichen")),
        (("v. change"), ("verändern")),
        (("v. develop"), ("entwickeln")),
        (("v. forget"), ("vergesse")),
        (("v. prevent"), ("verhindern")),
        (("v. concerns"), ("betrifft")),
        (("v. answered"), ("beantwortet")),
        (("v. answer"), ("beantworten")),
        (("v. calculated"), ("berechnet")),
        (("v. affect"), ("betreffen")),
    ]
}
duolingo_set_20 = {
    'name' : 'Duolingo Set 20',
    'words' : [
        (("v. to report"), ("berichten")),
        (("v. receives"), ("erhält")),
        (("v. experience"), ("erleben")),
        (("v. to reach"), ("erreichen")),
        (("v. appears"), ("erscheint")),
        (("v. expect"), ("erwarten")),
        (("v. determined"), ("ermittelt")),
        (("v. do"), ("tue")),
        (("v. deserve"), ("verdiene")),
        (("v. serve"), ("dienen")),
        (("v. check"), ("überprüfen")),
        (("v. evaluate"), ("bewerten")),
        (("v. eighth"), ("achte")),
        (("v. are defined"), ("definiert")),
        (("v. to contact"), ("kontaktieren")),
        (("v. based"), ("basiert")),
        (("v. report"), ("melden")),
        (("v. to back up"), ("sichern")),
        (("v. ask"), ("bitten")),
        (("v. talks"), ("redet")),
        (("v. jump"), ("springe")),
        (("v. leap"), ("springen")),
        (("v. notice"), ("merken")),
        (("harmless"), ("harmlos")),
        (("dangerous"), ("gefährlich")),
        (("insane"), ("verrückt")),
        (("the cows"), ("die Kühe")),
        (("the mice"), ("die Mäuse")),
        (("greater"), ("größer")),
        (("completely"), ("völlig")),
    ]
}
duolingo_set_21 = {
    'name' : 'Duolingo Set 21',
    'words' : [
        (("smart"), ("schlau")),
        (("stupid"), ("dumm")),
        (("the girl"), ("das Mädchen")),
        (("the pig"), ("das Schwein")),
        (("the sheep"), ("das Schaf")),
        (("the snake"), ("die Schlange")),
        (("v. stings"), ("sticht")),
        (("v. sting"), ("stechen")),
        (("the wasp"), ("die Wespe")),
        (("the tiger"), ("der Tiger")),
        (("the horns"), ("die Hörner")),
        (("the whales"), ("die Wale")),
        (("the zebra"), ("das Zebra")),
        (("v. rode"), ("reitet")),
        (("the hamster"), ("der Hamster")),
        (("the giraffe"), ("die Giraffe")),
        (("ninety"), ("neunzig")),
        (("the penguins"), ("die Pinguine")),
        (("the mammal"), ("das Säugetier")),
        (("the camels"), ("die Kamele")),
        (("the camel"), ("das Kamel")),
        (("the geese"), ("die Gänse")),
        (("the butterflies"), ("die Schmetterlinge")),
        (("v. bite"), ("beißen")),
        (("the fox"), ("der Fuchs")),
        (("the owl"), ("die Eule")),
        (("the squirrel"), ("das Eichhörnchen")),
        (("the sheep"), ("das Schafe")),
        (("the goose"), ("die Gans")),
        (("hans"), ("hans")),
    ]
}
duolingo_set_22 = {
    'name' : 'Duolingo Set 22',
    'words' : [
        (("normal"), ("normal")),
        (("relative"), ("relativ")),
        (("dependent"), ("abhängig")),
        (("public"), ("öffentlichen")),
        (("at all"), ("überhaupt")),
        (("not correct"), ("falsch")),
        (("the attempt"), ("der Versuch")),
        (("visible"), ("sichtbar")),
        (("the opportunity"), ("die Gelegenheit")),
        (("super"), ("super")),
        (("makes sense"), ("sinnvoll")),
        (("therefore"), ("daher")),
        (("however"), ("jedoch")),
        (("barely"), ("kaum")),
        (("first"), ("zuerst")),
        (("the engagement"), ("die Engagement")),
        (("the recommendation"), ("die Empfehlung")),
        (("the hints"), ("die Hinweise")),
        (("the quality"), ("die Qualität")),
        (("the collaboration"), ("die Zusammenarbeit")),
        (("the dimensions"), ("die Maße")),
        (("the security"), ("die Sicherheit")),
        (("the results"), ("die Ergebnisse")),
        (("the help"), ("die Hilfe")),
        (("the development"), ("die Entwicklung")),
        (("the competence"), ("die Kompetenz")),
        (("the recommendations"), ("die Empfehlungen")),
        (("the selection"), ("die Auswahl")),
        (("the use"), ("die Nutzen")),
        (("the pressure"), ("der Druck")),
    ]
}
duolingo_set_23 = {
    'name' : 'Duolingo Set 23',
    'words' : [
        (("the location"), ("der Lage")),
        (("the wise"), ("der Weise")),
        (("the aims"), ("die Ziele")),
        (("the modification"), ("die Änderung")),
        (("the note"), ("die Hinweis")),
        (("the behavior"), ("das Verhalten")),
        (("the problem"), ("das Problem")),
        (("the solutions"), ("die Lösungen")),
        (("the shape"), ("die Form")),
        (("otherwise"), ("sonst")),
        (("v. walk"), ("gehen")),
        (("of course"), ("selbstverständlich")),
        (("either"), ("sowohl")),
        (("individual"), ("individuelle")),
        (("them"), ("ihnen")),
        (("thirty"), ("dreißig")),
        (("the terms"), ("die Begriffe")),
        (("general"), ("allgemein")),
        (("rather"), ("eher")),
        (("the word"), ("das Wort")),
        (("the idea"), ("die Idee")),
        (("the words"), ("die Wörter")),
        (("the languages"), ("die Sprachen")),
        (("detailed"), ("detaillierte")),
        (("the term"), ("der Begriff")),
        (("the translation"), ("die Übersetzung")),
        (("the entertainment"), ("die Unterhaltung")),
        (("the summary"), ("die Zusammenfassung")),
        (("v. means"), ("bedeutet")),
        (("the sentence"), ("der Satz")),
    ]
}
duolingo_set_24 = {
    'name' : 'Duolingo Set 24',
    'words' : [
        (("the chapter"), ("das Kapitel")),
        (("the directory"), ("das Verzeichnis")),
        (("the character"), ("der Zeichen")),
        (("the explanation"), ("die Erklärung")),
        (("the opinion"), ("die Meinung")),
        (("the opinions"), ("die Meinungen")),
        (("the concept"), ("das Konzept")),
        (("the title"), ("der Titel")),
        (("the approval"), ("die Zustimmung")),
        (("the story"), ("die Geschichte")),
        (("the texts"), ("die Texte")),
        (("the reports"), ("die Berichte")),
        (("the text"), ("der Text")),
        (("v. tell"), ("erzähle")),
        (("the stories"), ("die Geschichten")),
        (("the report"), ("der Bericht")),
        (("the ideas"), ("die Ideen")),
        (("the font"), ("die Schrift")),
        (("the importance"), ("die Bedeutung")),
        (("the description"), ("die Beschreibung")),
        (("colorful"), ("bunt")),
        (("brown"), ("braun")),
        (("great"), ("großartig")),
        (("various"), ("verschiedene")),
        (("highest"), ("höchste")),
        (("further"), ("weiterer")),
        (("enough"), ("genug")),
        (("v. offers"), ("bietet")),
        (("the commandments"), ("die Gebote")),
        (("the colleagues"), ("die Kollegen")),
    ]
}
duolingo_set_25 = {
    'name' : 'Duolingo Set 25',
    'words' : [
        (("the value"), ("der Wert")),
        (("the projects"), ("die Projekte")),
        (("the canditature"), ("die Bewerbung")),
        (("the career"), ("die Karriere")),
        (("the job"), ("die Job")),
        (("the jobs"), ("die Jobs")),
        (("gray"), ("grau")),
        (("the man"), ("der Mannes")),
        (("the trade"), ("der Handel")),
        (("the win"), ("der Gewinne")),
        (("the profit"), ("der Gewinn")),
        (("the consumer"), ("der Verbraucher")),
        (("the purchase"), ("der Kauf")),
        (("the purchases"), ("die Käufe")),
        (("the buyers"), ("die Käufer")),
        (("the rental fee"), ("die Miete")),
        (("the documents"), ("die Dokumente")),
        (("the posts"), ("die Beiträge")),
        (("the competition"), ("der Wettbewerb")),
        (("the project"), ("das Projekt")),
        (("the management"), ("das Management")),
        (("the orders"), ("die Bestellungen")),
        (("the consultation"), ("die Beratung")),
        (("the bid"), ("das Gebot")),
        (("v. offer"), ("bieten")),
        (("the shares"), ("die Aktien")),
        (("v. rent"), ("mieten")),
        (("the order"), ("die Bestellung")),
        (("the organization"), ("die Organisation")),
        (("the factory"), ("die Fabrik")),
    ]
}
duolingo_set_26 = {
    'name' : 'Duolingo Set 26',
    'words' : [
        (("the office"), ("das Büro")),
        (("the companies"), ("die Unternehmen")),
        (("the owner"), ("der Inhaber")),
        (("the membership"), ("die Mitgliedschaft")),
        (("the factories"), ("die Fabriken")),
        (("thirteen"), ("dreizehn")),
        (("additional"), ("zusätzliche")),
        (("left"), ("linken")),
        (("the mailbox"), ("der Briefkasten")),
        (("v. publish"), ("veröffentlichen")),
        (("the contacts"), ("die Kontakte")),
        (("the letters"), ("die Briefe")),
        (("the message"), ("die Mitteilung")),
        (("the radios"), ("die Radios")),
        (("the messages"), ("die Mitteilungen")),
        (("the registration"), ("die Anmeldung")),
        (("the speaker"), ("der Lautsprecher")),
        (("the channel"), ("der Sender")),
        (("the subjects"), ("die Themen")),
        (("the reason"), ("der Begründung")),
        (("the confirmation"), ("die Bestätigung")),
        (("the messages"), ("die Meldungen")),
        (("the publishing company"), ("der Verlag")),
        (("v. released"), ("veröffentlicht")),
        (("v. send"), ("senden")),
        (("the contact"), ("der Kontakt")),
        (("the invitations"), ("die Einladungen")),
        (("the invitation"), ("die Einladung")),
        (("the letter"), ("der Brief")),
        (("the address"), ("die Adresse")),
    ]
}
duolingo_set_27 = {
    'name' : 'Duolingo Set 27',
    'words' : [
        (("the salutation"), ("die Anrede")),
        (("the note"), ("die Notiz")),
        (("the greetings"), ("die Grüße")),
        (("back"), ("hinten")),
        (("finished"), ("fertig")),
        (("well"), ("wohl")),
        (("the women"), ("die Frauen")),
        (("including"), ("einschließlich")),
        (("around"), ("ums")),
        (("someone"), ("jemand")),
        (("while"), ("während")),
        (("the birds"), ("die Vögel")),
        (("somewhere"), ("irgendwo")),
        (("across from"), ("gegenüber")),
        (("unfortunately"), ("leider")),
        (("either"), ("entweder")),
        (("v. swim"), ("schwimmen")),
        (("absolutely"), ("durchaus")),
        (("twelve"), ("zwölf")),
        (("on"), ("auf")),
        (("it"), ("es")),
        (("the analysis"), ("die Analyse")),
        (("the scientist"), ("der Wissenschaftlerin")),
        (("at least"), ("zumindest")),
        (("the radiation"), ("die Strahlung")),
        (("the knowledge"), ("das Kenntnis")),
        (("so"), ("also")),
        (("the proof"), ("der Nachweis")),
        (("the plastic"), ("der Kunststoff")),
        (("the the atmosphere"), ("die Atmosphäre")),
    ]
}
duolingo_set_28 = {
    'name' : 'Duolingo Set 28',
    'words' : [
        (("the analyzes"), ("die Analysen")),
        (("the gas"), ("das Gas")),
        (("the textbooks"), ("die Lehrbücher")),
        (("v. test"), ("teste")),
        (("v. testing"), ("testen")),
        (("the internships"), ("die Praktika")),
        (("the method"), ("die Methode")),
        (("the methods"), ("die Methoden")),
        (("the internship"), ("das Praktikum")),
        (("the scientists"), ("die Wissenschaftlerinnen")),
        (("the elements"), ("die Elemente")),
        (("the technology"), ("die Technik")),
        (("the machinery"), ("die Maschinen")),
        (("the knowledge"), ("das Wissen")),
        (("the statistics"), ("die Statistiken")),
        (("the studies"), ("die Studien")),
        (("the temperature"), ("die Temperatur")),
        (("v. measure up"), ("messen")),
        (("the energy"), ("die Energie")),
        (("the engine"), ("der Motor")),
        (("the engines"), ("die Motoren")),
        (("v. fair"), ("messe")),
        (("the science"), ("die Wissenschaft")),
        (("the inventions"), ("die Erfindungen")),
        (("the theory"), ("die Theorie")),
        (("the invention"), ("die Erfindung")),
        (("the definitions"), ("die Definitionen")),
        (("the knowledge"), ("das Kenntnisse")),
        (("the definition"), ("die Definition")),
        (("well"), ("naja")),
    ]
}
duolingo_set_29 = {
    'name' : 'Duolingo Set 29',
    'words' : [
        (("quite"), ("ziemlich")),
        (("the forgiveness"), ("die Verzeihung")),
        (("it"), ("es")),
        (("where"), ("wohin")),
        (("eleven"), ("elf")),
        (("fifteen"), ("fünfzehn")),
        (("the dozen"), ("das Dutzend")),
        (("nineteen"), ("neunzehn")),
        (("the idea"), ("die Ahnung")),
        (("after this"), ("nachdem")),
        (("automatically"), ("automatisch")),
        (("old"), ("alte")),
        (("fewer"), ("weniger")),
        (("none"), ("keinerlei")),
        (("the more"), ("desto")),
        (("frequently"), ("häufig")),
        (("back then"), ("damals")),
        (("sixty"), ("sechzig")),
        (("v. quarter"), ("viertel")),
        (("neither"), ("weder")),
        (("the downtown areas"), ("die Innenstädte")),
        (("the areas"), ("die Bereiche")),
        (("the plastic"), ("der Plastik")),
        (("more quickly"), ("schneller")),
        (("expensive"), ("teurer")),
        (("second"), ("zweiten")),
        (("angry"), ("sauer")),
        (("the courses"), ("die Kurse")),
        (("the seminars"), ("die Seminare")),
        (("the pencils"), ("die Stifte")),
    ]
}
duolingo_set_30 = {
    'name' : 'Duolingo Set 30',
    'words' : [
        (("the grades"), ("die Noten")),
        (("rest"), ("übrigen")),
        (("sad"), ("traurig")),
        (("the education"), ("die Erziehung")),
        (("the exams"), ("die Prüfungen")),
        (("v. think"), ("überlege")),
        (("the subject area"), ("der Fachbereich")),
        (("the university"), ("die Uni")),
        (("the further education"), ("die Weiterbildung")),
        (("the exam"), ("die Prüfung")),
        (("the kindergarten"), ("der Kindergarten")),
        (("the high school"), ("gymnasium Gymnasium")),
        (("the institute"), ("das Institute")),
        (("v. to teach"), ("lehren")),
        (("the university"), ("die Hochschule")),
        (("the institute"), ("das Institut")),
        (("the classes"), ("die Unterricht")),
        (("the academy"), ("die Akademie")),
        (("the training"), ("das Ausbildung")),
        (("the colleges"), ("die Hochschulen")),
        (("the training"), ("das Training")),
        (("the great"), ("der Klassen")),
        (("the testing"), ("die Tests")),
        (("the great"), ("der Klasse")),
        (("the test"), ("der Test")),
        (("the course"), ("der Kurs")),
        (("the seminar"), ("das Seminar")),
        (("the research"), ("die Forschung")),
        (("the education"), ("die Studium")),
        (("independently"), ("unabhängig")),
    ]
}
duolingo_set_31 = {
    'name' : 'Duolingo Set 31',
    'words' : [
        (("the grade"), ("die Note")),
        (("the exercises"), ("die Übungen")),
        (("the pen"), ("der Stift")),
        (("the exercise"), ("die Übung")),
        (("the donate"), ("die Stiften")),
        (("the reader"), ("der Leser")),
        (("the education"), ("die Bildung")),
        (("the university"), ("die Universität")),
        (("seventy"), ("siebzig")),
        (("the networks"), ("die Netze")),
        (("just like that"), ("genauso")),
        (("down"), ("herunter")),
        (("social"), ("sozialen")),
        (("twenty eight"), ("achtundzwanzig")),
        (("to"), ("bis")),
        (("proud"), ("stolz")),
        (("total"), ("total")),
        (("boring"), ("langweilig")),
        (("creepy"), ("unheimlich")),
        (("funny"), ("witzig")),
        (("v. allow"), ("erlauben")),
        (("the keys"), ("die Tasten")),
        (("v. loading"), ("lade")),
        (("the picture"), ("das Bild")),
        (("the pictures"), ("die Bilder")),
        (("v. delete"), ("lösche")),
        (("the program"), ("das Programm")),
        (("v. clears"), ("löscht")),
        (("the programs"), ("die Programme")),
        (("v. to press"), ("drucken")),
    ]
}
duolingo_set_32 = {
    'name' : 'Duolingo Set 32',
    'words' : [
        (("the profile"), ("das Profile")),
        (("the passwords"), ("die Passwörter")),
        (("the profile"), ("das Profil")),
        (("v. to update"), ("aktualisieren")),
        (("v. updated"), ("aktualisiert")),
        (("v. prints"), ("drucke")),
        (("v. update"), ("aktualisiere")),
        (("the button"), ("die Taste")),
        (("the comment"), ("der Kommentar")),
        (("the comments"), ("die Kommentare")),
        (("v. sends"), ("schickt")),
        (("the attachments"), ("die Anhänge")),
        (("the attachment"), ("der Anhang")),
        (("the network"), ("das Netz")),
        (("v. load"), ("laden")),
        (("the pages"), ("die Seiten")),
        (("the internet"), ("das Internet")),
        (("v. loads"), ("lädt")),
        (("the photos"), ("die Fotos")),
        (("the photo"), ("das Foto")),
        (("the page"), ("die Seite")),
        (("cool"), ("kühl")),
        (("eighteen"), ("achtzehn")),
        (("since"), ("seit")),
        (("to"), ("bis")),
        (("dirty"), ("schmutzig")),
        (("nevertheless"), ("trotzdem")),
        (("the magazine"), ("die Zeitschrift")),
        (("cordial"), ("herzlich")),
        (("the talk"), ("das Reden")),
    ]
}
duolingo_set_33 = {
    'name' : 'Duolingo Set 33',
    'words' : [
        (("the media"), ("die Medien")),
        (("slower"), ("langsamer")),
        (("more important"), ("wichtiger")),
        (("v. start"), ("starte")),
        (("the speech"), ("die Rede")),
        (("the broadcast"), ("die Sendung")),
        (("the discussions"), ("die Diskussionen")),
        (("the medium"), ("das Medium")),
        (("the tv"), ("der Fernseher")),
        (("the broadcasts"), ("die Sendungen")),
        (("the watch tv"), ("die Fernsehen")),
        (("the discussion"), ("die Diskussion")),
        (("the articles"), ("die Artikeln")),
        (("the items"), ("die Artikel")),
        (("the interviews"), ("die Interviews")),
        (("the magazines"), ("die Zeitschriften")),
        (("the news"), ("die Nachrichten")),
        (("the press"), ("die Presse")),
        (("the interview"), ("das Interview")),
        (("the message"), ("die Nachricht")),
        (("the hard disk"), ("die Festplatte")),
        (("the hard drives"), ("die Festplatten")),
        (("the information"), ("die Information")),
        (("the monitor"), ("der Monitor")),
        (("the keyboards"), ("die Tastaturen")),
        (("v. starts"), ("startet")),
        (("the keyboard"), ("die Tastatur")),
        (("the monitors"), ("die Monitore")),
        (("the computer"), ("der Computer")),
        (("the cell phones"), ("die Handys")),
    ]
}
duolingo_set_34 = {
    'name' : 'Duolingo Set 34',
    'words' : [
        (("the phone"), ("das Telefon")),
        (("the communication"), ("die Kommunikation")),
        (("the telephones"), ("die Telefone")),
        (("the conversation"), ("die Gespräch")),
        (("the conversations"), ("die Gespräche")),
        (("the mobile phone"), ("das Handy")),
        (("the plan"), ("der Plan")),
        (("private"), ("privaten")),
        (("german"), ("deutschen")),
        (("second"), ("zweite")),
        (("the put"), ("der Stellen")),
        (("the catalogs"), ("die Kataloge")),
        (("the plans"), ("die Pläne")),
        (("sometime"), ("irgendwann")),
        (("anyone"), ("irgendwer")),
        (("anything"), ("irgendwas")),
        (("somehow"), ("irgendwie")),
        (("the packages"), ("die Pakete")),
        (("the ground"), ("der Boden")),
        (("the floors"), ("die Böden")),
        (("the package"), ("das Paket")),
        (("the gift"), ("das Geschenk")),
        (("the equipment"), ("die Zubehör")),
        (("the pieces"), ("die Stücke")),
        (("the piece"), ("das Stück")),
        (("the gifts"), ("die Geschenke")),
        (("the shear"), ("die Scheren")),
        (("the thing"), ("die Sache")),
        (("the product"), ("das Produkt")),
        (("the catalog"), ("der Katalog")),
    ]
}
duolingo_set_35 = {
    'name' : 'Duolingo Set 35',
    'words' : [
        (("the scissors"), ("die Schere")),
        (("the products"), ("die Produkte")),
        (("the job"), ("die Stelle")),
        (("the stuff"), ("das Sachen")),
        (("the products"), ("die Produkten")),
        (("clean"), ("sauber")),
        (("wet"), ("nass")),
        (("sixteen"), ("sechzehn")),
        (("together"), ("gemeinsam")),
        (("mostly"), ("meistens")),
        (("the cloud"), ("die Wolke")),
        (("longer"), ("länger")),
        (("the clouds"), ("die Wolken")),
        (("the rainbow"), ("der Regenbogen")),
        (("the flashes"), ("die Blitze")),
        (("the umbrellas"), ("die Regenschirme")),
        (("the umbrella"), ("der Regenschirm")),
        (("the lightning"), ("der Blitz")),
        (("the thunder"), ("der Donner")),
        (("the storm"), ("der Sturms")),
        (("the storm"), ("der Sturm")),
        (("the rain"), ("der Regen")),
        (("the weather"), ("das Wetter")),
        (("the degree"), ("das Grad")),
        (("ill"), ("krank")),
        (("more beautiful"), ("schöner")),
        (("impossible"), ("unmöglich")),
        (("previously"), ("vorher")),
        (("whole"), ("ganzen")),
        (("v. drinks"), ("trinkt")),
    ]
}
duolingo_set_36 = {
    'name' : 'Duolingo Set 36',
    'words' : [
        (("political"), ("politischen")),
        (("beautiful"), ("schönen")),
        (("personal"), ("persönliche")),
        (("free"), ("freien")),
        (("active"), ("aktive")),
        (("yellower"), ("gelber")),
        (("last"), ("letzten")),
        (("outside"), ("außen")),
        (("hundred"), ("hundert")),
        (("forty two"), ("zweiundvierzig")),
        (("thousand"), ("tausend")),
        (("one hundred twenty-three"), ("hundertdreiundzwanzig")),
        (("v. let"), ("ließen")),
        (("v. stayed"), ("blieben")),
        (("v. lost"), ("verloren")),
        (("v. wrote"), ("schrieben")),
        (("v. closed"), ("schlossen")),
        (("v. took"), ("nahmen")),
        (("v. gifts"), ("gaben")),
        (("v. thought"), ("dachtet")),
        (("v. languages"), ("sprachen")),
        (("v. read"), ("lasen")),
        (("v. lay"), ("lagen")),
        (("v. wait"), ("wart")),
        (("v. began"), ("begannt")),
        (("v. saw"), ("saht")),
        (("competent"), ("zuständigen")),
        (("open"), ("offenen")),
        (("v. showed"), ("zeigten")),
        (("v. has been"), ("wurde")),
    ]
}
duolingo_set_37 = {
    'name' : 'Duolingo Set 37',
    'words' : [
        (("v. had"), ("hatten")),
        (("v. were"), ("wurden")),
        (("v. was standing"), ("stand")),
        (("v. could"), ("konnte")),
        (("v. had to"), ("mussten")),
        (("v. said"), ("sagte")),
        (("v. led"), ("führte")),
        (("v. made"), ("machte")),
        (("v. walked"), ("spazierte")),
        (("v. worked"), ("arbeiteten")),
        (("v. posed"), ("stellte")),
        (("v. slept"), ("schlief")),
        (("v. received"), ("erhielten")),
        (("v. to lead"), ("fuhren")),
        (("v. lock"), ("schloss")),
        (("v. found"), ("fanden")),
        (("v. gave"), ("gab")),
        (("v. spoke"), ("sprach")),
        (("v. went"), ("ging")),
        (("v. came"), ("kam")),
        (("v. sponge"), ("schwamm")),
        (("v. ate"), ("aß")),
        (("v. started"), ("begann")),
        (("v. eats"), ("aßt")),
        (("v. swam"), ("schwammen")),
        (("v. drank"), ("trank")),
        (("because"), ("denn")),
        (("actually"), ("eigentlich")),
        (("otherwise"), ("ansonsten")),
        (("by the way"), ("übrigens")),
    ]
}
duolingo_set_38 = {
    'name' : 'Duolingo Set 38',
    'words' : [
        (("indeed"), ("allerdings")),
        (("at least"), ("wenigstens")),
        (("inside"), ("drin")),
        (("at the same time"), ("zugleich")),
        (("the operator"), ("der Betreiber")),
        (("the specialties"), ("die Spezialitäten")),
        (("fourteen"), ("vierzehn")),
        (("swiss"), ("schweizer")),
        (("most of time"), ("meist")),
        (("eighty-two"), ("zweiundachtzig")),
        (("twenty"), ("zwanzig")),
        (("twenty-one"), ("einundzwanzig")),
        (("twentythree"), ("dreiundzwanzig")),
        (("twenty four"), ("vierundzwanzig")),
        (("seventeen"), ("siebzehn")),
        (("thirty-two"), ("zweiunddreißig")),
        (("theirs"), ("ihres")),
        (("his"), ("seines")),
        (("external"), ("externe")),
        (("strengthen"), ("starken")),
        (("public"), ("öffentliches")),
        (("social"), ("soziales")),
        (("v. donate"), ("schenke")),
        (("v. gives"), ("schenkt")),
        (("additional"), ("zusätzlichen")),
        (("same"), ("gleichen")),
        (("boys"), ("jungen")),
        (("next"), ("nächste")),
        (("simple"), ("einfachen")),
        (("greatest"), ("größte")),
    ]
}
duolingo_set_39 = {
    'name' : 'Duolingo Set 39',
    'words' : [
        (("biggest"), ("größten")),
        (("international"), ("internationalen")),
        (("current"), ("aktuelle")),
        (("new"), ("neuen")),
        (("former"), ("ehemalige")),
        (("old"), ("alten")),
        (("latest"), ("neuesten")),
        (("simple"), ("einfache")),
        (("cheap"), ("günstige")),
        (("last"), ("zuletzt")),
        (("sharp"), ("scharf")),
        (("available"), ("verfügbaren")),
        (("english"), ("englische")),
        (("out"), ("heraus")),
        (("in"), ("herein")),
        (("on road"), ("unterwegs")),
        (("yours"), ("deines")),
        (("yours"), ("deiner")),
        (("fourty"), ("vierzig")),
        (("eighty"), ("achtzig")),
        (("fifty"), ("fünfzig")),
        (("far"), ("weit")),
        (("necessary"), ("notwendigen")),
        (("the west"), ("der Westen")),
        (("the direction"), ("die Richtung")),
        (("the south"), ("der Süden")),
        (("the east"), ("der Osten")),
        (("the north"), ("der Norden")),
        (("v. bend"), ("bieg")),
        (("v. bends"), ("biegt")),
    ]
}
duolingo_set_40 = {
    'name' : 'Duolingo Set 40',
    'words' : [
        (("v. give"), ("schenken")),
        (("further"), ("weitere")),
        (("single"), ("einzige")),
        (("important"), ("wichtige")),
        (("modern"), ("modernen")),
        (("technical"), ("technischen")),
        (("free"), ("kostenlose")),
        (("private"), ("private")),
        (("most important"), ("wichtigsten")),
        (("random"), ("zufälliger")),
        (("normal"), ("normalen")),
        (("next"), ("nächster")),
        (("teenagers"), ("jugendliche")),
        (("brave"), ("tapfer")),
        (("the expert"), ("der Experte")),
        (("the lawyers"), ("die Rechtsanwälte")),
        (("the specialty"), ("die Spezialität")),
        (("the lawyer"), ("der Rechtsanwalt")),
        (("the judge"), ("der Richter")),
        (("the experts"), ("die Experten")),
        (("the cutter"), ("der Schneider")),
        (("the workshop"), ("der Werkstatt")),
        (("the craft"), ("das Handwerk")),
        (("the manufacturer"), ("der Hersteller")),
        (("the author"), ("der Verfasser")),
        (("the participants"), ("die Teilnehmern")),
        (("the receiver"), ("der Empfänger")),
        (("the staff"), ("das Personal")),
        (("the developer"), ("der Entwickler")),
        (("the attendees"), ("die Teilnehmer")),
    ]
}
duolingo_set_41 = {
    'name' : 'Duolingo Set 41',
    'words' : [
        (("v. happen"), ("geschehen")),
        (("the ice"), ("das Eis")),
        (("the thirst"), ("der Durst")),
        (("fit"), ("fit")),
        (("suddenly"), ("plötzlich")),
        (("of their"), ("ihrer")),
        (("the house"), ("das Hauses")),
        (("the stream"), ("der Ströme")),
        (("the deserts"), ("die Wüsten")),
        (("the rivers"), ("die Flüsse")),
        (("the brooks"), ("die Bäche")),
        (("the forests"), ("die Wälder")),
        (("rhine"), ("rhein")),
        (("the grasslands"), ("das Wiesen")),
        (("the grasses"), ("die Gräser")),
        (("the climate"), ("das Klima")),
        (("the plant"), ("die Pflanze")),
        (("the electricity"), ("der Strom")),
        (("the agriculture"), ("die Landwirtschaft")),
        (("the desert"), ("die Wüste")),
        (("the plants"), ("die Pflanzen")),
        (("the alles"), ("das All")),
        (("the forest"), ("der Wald")),
        (("the bach"), ("der Bach")),
        (("the meadow"), ("die Wiese")),
        (("the grass"), ("das Gras")),
        (("the wildlife"), ("das Tierwelt")),
        (("the environment"), ("die Umwelt")),
        (("the beaches"), ("die Strände")),
        (("the amber"), ("der Bernstein")),
    ]
}
duolingo_set_42 = {
    'name' : 'Duolingo Set 42',
    'words' : [
        (("the lake"), ("der See")),
        (("the wave"), ("die Welle")),
        (("the world"), ("die Welt")),
        (("the beach"), ("der Strand")),
        (("the waves"), ("die Wellen")),
        (("the air"), ("die Luft")),
        (("approximately"), ("etwa")),
        (("the reason"), ("der Grund")),
        (("v. expand"), ("erweitere")),
        (("v. take over"), ("übernehme")),
        (("individually"), ("individuell")),
        (("known"), ("bekannt")),
        (("extreme"), ("extrem")),
        (("soft"), ("weich")),
        (("hard"), ("hart")),
        (("no later than"), ("spätestens")),
        (("fresh"), ("frisch")),
        (("the places"), ("die Orte")),
        (("the federal states"), ("die Bundesländer")),
        (("the capital cities"), ("die Hauptstädte")),
        (("the holiday homes"), ("die Ferienhäuser")),
        (("the echo"), ("das Hallen")),
        (("the downtown"), ("die Innenstadt")),
        (("most"), ("meisten")),
        (("bigger"), ("größeren")),
        (("the times"), ("die Mal")),
        (("numerous"), ("zahlreiche")),
        (("bigger"), ("größeres")),
        (("few"), ("wenigen")),
        (("few"), ("wenige")),
    ]
}
duolingo_set_43 = {
    'name' : 'Duolingo Set 43',
    'words' : [
        (("nearly"), ("fast")),
        (("at night"), ("nachts")),
        (("half"), ("halb")),
        (("firmly"), ("fest")),
        (("the seconds"), ("die Sekunden")),
        (("the second"), ("der Sekunde")),
        (("the time"), ("die Uhrzeit")),
        (("the clocks"), ("die Uhren")),
        (("the duration"), ("die Dauer")),
        (("the time"), ("die Zeitpunkt")),
        (("v. last"), ("dauern")),
        (("the midnight"), ("die Mitternacht")),
        (("the time"), ("die Zeit")),
        (("the clock"), ("die Uhr")),
        (("the moment"), ("der Augenblick")),
        (("the hours"), ("die Stunden")),
        (("the times"), ("die Zeiten")),
        (("the hour"), ("die Stunde")),
        (("the minute"), ("die Minute")),
        (("the minutes"), ("die Minuten")),
        (("the evenings"), ("die Abende")),
        (("the period"), ("die Zeitraum")),
        (("the night"), ("die Nacht")),
        (("the eve"), ("der Abend")),
        (("the nights"), ("die Nächte")),
        (("the tomorrow"), ("das Morgen")),
        (("the noon"), ("der Mittag")),
        (("the events"), ("die Termine")),
        (("the moment"), ("der Moment")),
        (("the moments"), ("die Momente")),
    ]
}
duolingo_set_44 = {
    'name' : 'Duolingo Set 44',
    'words' : [
        (("the meeting"), ("das Termin")),
        (("v. laughs"), ("lacht")),
        (("the owe"), ("die Schulden")),
        (("the favorite"), ("der Liebling")),
        (("v. laugh"), ("lache")),
        (("the understanding"), ("das Verständnis")),
        (("the happiness"), ("die Glück")),
        (("the favourite"), ("der Lieblings")),
        (("v. to hate"), ("hassen")),
        (("the lust"), ("die Lust")),
        (("funny"), ("lustig")),
        (("the trouble"), ("die Ärger")),
        (("the thoughts"), ("die Gedanken")),
        (("the joke"), ("der Witz")),
        (("the thought"), ("der Gedanke")),
        (("the humor"), ("der Humor")),
        (("the quiet"), ("die Ruhe")),
        (("the dentist"), ("der Zahnarzt")),
        (("the locations"), ("die Standorte")),
        (("the foreign countries"), ("das Ausland")),
        (("the centers"), ("die Zentren")),
        (("the impression"), ("der Eindruck")),
        (("the anxiety"), ("die Angst")),
        (("the fun"), ("der Spaß")),
        (("the serious"), ("das Ernst")),
        (("v. loves"), ("liebt")),
        (("v. love"), ("liebe")),
        (("v. dream"), ("träumen")),
        (("the wish"), ("der Wunsch")),
        (("v. dreams"), ("träumt")),
    ]
}
duolingo_set_45 = {
    'name' : 'Duolingo Set 45',
    'words' : [
        (("the wishes"), ("die Wünsche")),
        (("the love"), ("die Liebe")),
        (("the not"), ("das Not")),
        (("the dreams"), ("die Träume")),
        (("the joy"), ("die Freude")),
        (("the dream"), ("der Traum")),
        (("quality"), ("gute")),
        (("good"), ("guten")),
        (("the toy"), ("das Spielzeug")),
        (("the january"), ("der Januar")),
        (("the september"), ("der September")),
        (("the christmas"), ("weihnachten Weihnachten")),
        (("the winter"), ("der Winter")),
        (("the data"), ("die Daten")),
        (("the quarter"), ("das Quartal")),
        (("the quarters"), ("die Quartale")),
        (("the phases"), ("die Phasen")),
        (("the enough"), ("das Schluss")),
        (("the age"), ("das Alter")),
        (("the birthday"), ("der Geburtstag")),
        (("the century"), ("das Jahrhundert")),
        (("the birthdays"), ("die Geburtstage")),
        (("the phase"), ("die Phase")),
        (("the centuries"), ("die Jahrhunderte")),
        (("v. ends"), ("endet")),
        (("the season"), ("die Saison")),
        (("the february"), ("der Februar")),
        (("latest"), ("letzte")),
        (("the seasons"), ("die Jahreszeiten")),
        (("the november"), ("der November")),
    ]
}
duolingo_set_46 = {
    'name' : 'Duolingo Set 46',
    'words' : [
        (("the date"), ("das Datum")),
        (("the calendar"), ("der Kalender")),
        (("the autumn"), ("der Herbst")),
        (("the july"), ("der Juli")),
        (("the year"), ("das Jahr")),
        (("the june"), ("der Juni")),
        (("the summer"), ("der Sommer")),
        (("the august"), ("der August")),
        (("the years"), ("die Jahre")),
        (("the years"), ("die Jahren")),
        (("the spring"), ("der Frühling")),
        (("the march"), ("der März")),
        (("the month"), ("der Monat")),
        (("the months"), ("die Monate")),
        (("the may"), ("der Mai")),
        (("the months"), ("die Monaten")),
        (("the april"), ("der April")),
        (("the asparagus"), ("der Spargel")),
        (("the pair"), ("das Paar")),
        (("the population"), ("die Bevölkerung")),
        (("the couples"), ("die Paare")),
        (("the residents"), ("die Einwohner")),
        (("the local community"), ("die Gemeinde")),
        (("the society"), ("die Verein")),
        (("the links"), ("die Verbindungen")),
        (("the societies"), ("die Vereine")),
        (("the municipalities"), ("die Gemeinden")),
        (("the connection"), ("die Verbindung")),
        (("the users"), ("die Nutzer")),
        (("the publicity"), ("die Öffentlichkeit")),
    ]
}
duolingo_set_47 = {
    'name' : 'Duolingo Set 47',
    'words' : [
        (("the relationship"), ("die Verhältnis")),
        (("v. watch"), ("schauen")),
        (("v. to use"), ("benutzen")),
        (("v. stand"), ("stehen")),
        (("v. waiting"), ("warten")),
        (("v. takes"), ("nimmt")),
        (("v. work"), ("arbeiten")),
        (("v. looks"), ("schaut")),
        (("v. steal"), ("stehle")),
        (("v. look"), ("schaue")),
        (("v. replace"), ("ersetze")),
        (("v. meet"), ("trefft")),
        (("v. lie"), ("liege")),
        (("v. hopes"), ("hofft")),
        (("the shirts"), ("die Hemden")),
        (("v. collects"), ("sammelt")),
        (("v. increases"), ("steigt")),
        (("v. steals"), ("stehlt")),
        (("v. checks"), ("prüft")),
        (("v. my"), ("meine")),
        (("v. is missing"), ("fehlt")),
        (("v. climb"), ("steigen")),
        (("v. collect"), ("sammeln")),
        (("v. absence"), ("fehlen")),
        (("v. accept"), ("akzeptiere")),
        (("v. subscribed"), ("abonniert")),
        (("v. accepted"), ("akzeptiert")),
        (("v. happens"), ("passiert")),
        (("v. walks"), ("spaziert")),
        (("v. subscribe"), ("abonniere")),
    ]
}
duolingo_set_48 = {
    'name' : 'Duolingo Set 48',
    'words' : [
        (("v. to stroll"), ("spazieren")),
        (("v. subscribe to"), ("abonnieren")),
        (("v. ordered"), ("bestellt")),
        (("v. shut down"), ("schließen")),
        (("v. recognizes"), ("erkennt")),
        (("v. allowed"), ("erlaubt")),
        (("v. takes over"), ("übernimmt")),
        (("v. to order"), ("bestellen")),
        (("v. used"), ("benutzt")),
        (("v. detect"), ("erkennen")),
        (("v. miss"), ("verpassen")),
        (("v. replaced"), ("ersetzt")),
        (("v. represents"), ("stellt")),
        (("v. believe"), ("glauben")),
        (("v. seems"), ("scheint")),
        (("v. lies"), ("liegt")),
        (("v. faith"), ("glaube")),
        (("v. believes"), ("glaubt")),
        (("v. to meet"), ("treffen")),
        (("v. stands"), ("steht")),
        (("v. put"), ("stellen")),
        (("v. meets"), ("trifft")),
        (("v. remains"), ("bleibt")),
        (("v. to take"), ("nehmen")),
        (("v. changes"), ("ändert")),
        (("v. like"), ("gefallen")),
        (("v. can"), ("kann")),
        (("v. knowledge"), ("wissen")),
        (("v. hope"), ("hoffe")),
        (("v. hold"), ("halten")),
    ]
}
duolingo_set_49 = {
    'name' : 'Duolingo Set 49',
    'words' : [
        (("v. to hope"), ("hoffen")),
        (("v. holds"), ("hält")),
        (("v. to sing"), ("singen")),
        (("v. know"), ("weißt")),
        (("v. white"), ("weiß")),
        (("v. is working"), ("arbeitet")),
        (("v. sing"), ("singe")),
        (("v. sings"), ("singt")),
        (("the wheelchairs"), ("die Rollstühle")),
        (("the diet"), ("die Diät")),
        (("the therapy"), ("die Therapie")),
        (("the nutrition"), ("die Ernährung")),
        (("the alcohol"), ("der Alkohol")),
        (("the clinic"), ("die Klinik")),
        (("the accident"), ("der Unfall")),
        (("the emergencies"), ("die Notfälle")),
        (("bad"), ("schlechte")),
        (("the sacrifice"), ("das Opfern")),
        (("the dentist"), ("der Zahnärztin")),
        (("the accidents"), ("die Unfälle")),
        (("the emergency"), ("der Notfall")),
        (("the victim"), ("das Opfer")),
        (("the ambulance"), ("der Krankenwagen")),
        (("the hospitals"), ("die Krankenhäuser")),
        (("the health insurance"), ("die Krankenversicherung")),
        (("the medicine"), ("die Medizin")),
        (("the hospital"), ("das Krankenhaus")),
        (("the investigations"), ("die Untersuchungen")),
        (("the diseases"), ("die Krankheiten")),
        (("the health"), ("die Gesundheit")),
    ]
}
duolingo_set_50 = {
    'name' : 'Duolingo Set 50',
    'words' : [
        (("the forms"), ("die Formulare")),
        (("the illness"), ("die Krankheit")),
        (("the practice"), ("die Praxis")),
        (("the form"), ("die Formular")),
        (("the examination"), ("die Untersuchung")),
        (("v. blossom"), ("blute")),
        (("the patient"), ("der Patient")),
        (("v. blossoms"), ("bluten")),
        (("the patients"), ("die Patienten")),
        (("the drugs"), ("die Medikamente")),
        (("the band aid"), ("das Pflaster")),
        (("v. bleeds"), ("blutet")),
        (("the wheelchair"), ("der Rollstuhl")),
        (("the drug"), ("das Medikament")),
        (("the places"), ("die Plätze")),
        (("the surfaces"), ("die Flächen")),
        (("the pubs"), ("die Kneipen")),
        (("the reasons"), ("die Gründe")),
        (("the districts"), ("die Bezirke")),
        (("next door"), ("nebenan")),
        (("strange"), ("seltsam")),
        (("small"), ("kleines")),
        (("the islands"), ("die Inseln")),
        (("the capital"), ("die Hauptstadt")),
        (("europe"), ("europa")),
        (("the inner"), ("das Innere")),
        (("the homeland"), ("das Heimat")),
        (("the holiday home"), ("das Ferienhaus")),
        (("the island"), ("die Insel")),
        (("the surroundings"), ("die Umgebung")),
    ]
}
duolingo_set_51 = {
    'name' : 'Duolingo Set 51',
    'words' : [
        (("the area"), ("das Fläche")),
        (("the property"), ("die Grundstück")),
        (("the courtyards"), ("die Höfe")),
        (("the center"), ("das Zentrum")),
        (("the central"), ("die Zentrale")),
        (("the hall"), ("die Halle")),
        (("the court"), ("das Hof")),
        (("the region"), ("die Region")),
        (("the district"), ("das Bezirk")),
        (("the regions"), ("die Regionen")),
        (("the state"), ("der Bundesland")),
        (("the location"), ("der Standort")),
        (("the airport"), ("der Flughafen")),
        (("the accommodation"), ("die Unterkunft")),
        (("the area"), ("das Bereich")),
        (("the areas"), ("die Bereichen")),
        (("the place"), ("der Ort")),
        (("the place"), ("der Platz")),
        (("the pub"), ("die Kneipe")),
        (("the pension"), ("die Pension")),
        (("over there"), ("drüben")),
        (("below"), ("unten")),
        (("inside"), ("innen")),
        (("inside"), ("drinnen")),
        (("original"), ("original")),
        (("goods"), ("guter")),
        (("the bear"), ("der Bären")),
        (("white"), ("weißen")),
        (("on"), ("dran")),
        (("the weekends"), ("die Wochenenden")),
    ]
}
duolingo_set_52 = {
    'name' : 'Duolingo Set 52',
    'words' : [
        (("the beginning"), ("der Anfang")),
        (("the past"), ("die Vergangenheit")),
        (("the everyday life"), ("der Alltag")),
        (("the the end"), ("das Ende")),
        (("the weekend"), ("das Wochenende")),
        (("the saturday"), ("der Samstag")),
        (("the sundays"), ("die Sonntage")),
        (("the week"), ("die Woche")),
        (("the weeks"), ("die Wochen")),
        (("the sunday"), ("der Sonntag")),
        (("the saturdays"), ("die Samstage")),
        (("the wednesday"), ("der Mittwoch")),
        (("the days"), ("die Tage")),
        (("the monday"), ("der Montag")),
        (("the tuesday"), ("der Dienstag")),
        (("the thursday"), ("der Donnerstag")),
        (("the day"), ("der Tag")),
        (("the meet"), ("das Tagen")),
        (("the friday"), ("der Freitag")),
        (("the cardboard boxes"), ("die Kartons")),
        (("the backpack"), ("der Rucksack")),
        (("the goal"), ("das Tor")),
        (("the refrigerators"), ("die Kühlschränke")),
        (("v. take a shower"), ("duschen")),
        (("the bath"), ("das Bad")),
        (("the backpacks"), ("die Rucksäcke")),
        (("the bowls"), ("die Schüsseln")),
        (("the rooms"), ("die Räume")),
        (("the toothbrush"), ("die Zahnbürste")),
        (("the take a shower"), ("die Duschen")),
    ]
}
duolingo_set_53 = {
    'name' : 'Duolingo Set 53',
    'words' : [
        (("the towels"), ("die Handtücher")),
        (("the towel"), ("das Handtuch")),
        (("the shower gel"), ("das Duschgel")),
        (("the shower"), ("die Dusche")),
        (("the soap"), ("die Seife")),
        (("v. takes a shower"), ("duscht")),
        (("the bottles"), ("die Flaschen")),
        (("the mirror"), ("der Spiegel")),
        (("the razor"), ("der Rasierer")),
        (("the bottle"), ("die Flasche")),
        (("the fridge"), ("der Kühlschrank")),
        (("the bowl"), ("die Schüssel")),
        (("the carton"), ("der Karton")),
        (("the toilet"), ("die Toilette")),
        (("the cup"), ("die Tasse")),
        (("the cups"), ("die Tassen")),
        (("the plate"), ("der Teller")),
        (("the toothpaste"), ("die Zahnpasta")),
        (("the battery"), ("die Batterie")),
        (("the ladder"), ("die Leiter")),
        (("the room"), ("der Raum")),
        (("the ladders"), ("die Leitern")),
        (("the glasses"), ("die Gläser")),
        (("the batteries"), ("die Batterien")),
        (("the glass"), ("das Glas")),
        (("the move"), ("die Umzug")),
        (("the equipment"), ("die Geräte")),
        (("the household"), ("der Haushalt")),
        (("the sleep"), ("der Schlaf")),
        (("the cleaning"), ("die Reinigung")),
    ]
}
duolingo_set_54 = {
    'name' : 'Duolingo Set 54',
    'words' : [
        (("the device"), ("das Gerät")),
        (("the heater"), ("die Heizung")),
        (("the domestic appliances"), ("die Haushaltsgeräte")),
        (("quiet"), ("leise")),
        (("good"), ("gutem")),
        (("best"), ("beste")),
        (("best"), ("besten")),
        (("better ones"), ("bessere")),
        (("better ones"), ("besseren")),
        (("good"), ("gutes")),
        (("good"), ("guten")),
        (("quality"), ("gute")),
        (("the shops"), ("die Geschäfte")),
        (("the bakeries"), ("die Bäckereien")),
        (("the voucher"), ("der Gutschein")),
        (("greater"), ("großer")),
        (("bigger"), ("größere")),
        (("fast"), ("schnelles")),
        (("the slug"), ("die Schnecke")),
        (("the sizes"), ("die Größen")),
        (("great"), ("großes")),
        (("size"), ("große")),
        (("the size"), ("die Größe")),
        (("small"), ("kleinen")),
        (("huge"), ("großen")),
        (("sixth"), ("sechste")),
        (("v. seventh"), ("siebte")),
        (("the mathematics"), ("die Mathematik")),
        (("first"), ("erster")),
        (("first"), ("erstes")),
    ]
}
duolingo_set_55 = {
    'name' : 'Duolingo Set 55',
    'words' : [
        (("first"), ("erste")),
        (("third"), ("dritten")),
        (("third"), ("dritte")),
        (("first"), ("ersten")),
        (("the metals"), ("die Metalle")),
        (("the metal"), ("das Metall")),
        (("the silver"), ("das Silber")),
        (("the gold"), ("das Gold")),
        (("the stole"), ("die Stahl")),
        (("the copper"), ("das Kupfer")),
        (("the wall"), ("die Mauer")),
        (("the cardboard"), ("der Pappe")),
        (("the papers"), ("die Papiere")),
        (("the leather"), ("das Leder")),
        (("the paper"), ("das Papier")),
        (("the cotton"), ("die Baumwolle")),
        (("the wood"), ("das Holz")),
        (("the walls"), ("die Mauern")),
        (("the wool"), ("die Wolle")),
        (("the concrete"), ("der Beton")),
        (("the stone"), ("der Stein")),
        (("the stones"), ("die Steine")),
        (("the books"), ("die Bücher")),
        (("the vehicles"), ("die Fahrzeuge")),
        (("the tools"), ("die Werkzeuge")),
        (("the toys"), ("die Spielzeuge")),
        (("the planes"), ("die Flugzeuge")),
        (("deep"), ("tief")),
        (("except"), ("außer")),
        (("because of"), ("wegen")),
    ]
}
duolingo_set_56 = {
    'name' : 'Duolingo Set 56',
    'words' : [
        (("at"), ("an")),
        (("behind"), ("hinter")),
        (("from"), ("ab")),
        (("next"), ("neben")),
        (("in front"), ("vor")),
        (("under"), ("unter")),
        (("about"), ("über")),
        (("between"), ("zwischen")),
        (("v. lays"), ("legt")),
        (("in"), ("in")),
        (("on"), ("auf")),
        (("the dealer"), ("der Händler")),
        (("the baker"), ("der Bäckerin")),
        (("the teacher"), ("der Lehrerin")),
        (("the halves"), ("die Hälften")),
        (("the pupil"), ("der Schülerin")),
        (("the architects"), ("die Architekten")),
        (("the bosses"), ("die Chefs")),
        (("the bosses"), ("die Chefinnen")),
        (("the trainer"), ("der Trainer")),
        (("the employer"), ("der Arbeitgeberin")),
        (("the employer"), ("der Arbeitgeber")),
        (("the female students"), ("die Studentinnen")),
        (("the professors"), ("die Professoren")),
        (("the college student"), ("der Student")),
        (("the cooks"), ("die Köchinnen")),
        (("the baker"), ("der Bäcker")),
        (("the seller"), ("der Verkäufer")),
        (("the fire department"), ("die Feuerwehr")),
        (("the architect"), ("der Architekt")),
    ]
}
duolingo_set_57 = {
    'name' : 'Duolingo Set 57',
    'words' : [
        (("the service"), ("der Bedienung")),
        (("the driver"), ("der Fahrer")),
        (("the farmers"), ("die Bauern")),
        (("the farmer"), ("der Bauer")),
        (("the author"), ("der Autor")),
        (("the senior"), ("der Senior")),
        (("the senior citizens"), ("die Senioren")),
        (("the boss"), ("der Chefin")),
        (("the master"), ("der Meister")),
        (("the mayor"), ("der Bürgermeister")),
        (("the employers"), ("die Arbeitgeberinnen")),
        (("the employees"), ("die Mitarbeiterinnen")),
        (("the chief executive officer"), ("der Geschäftsführer")),
        (("the job"), ("die Arbeit")),
        (("the colleague"), ("der Mitarbeiterin")),
        (("the work"), ("die Arbeiten")),
        (("the workers"), ("die Arbeitnehmer")),
        (("the employee"), ("der Mitarbeiter")),
        (("the professor"), ("der Professor")),
        (("the students"), ("die Schülerinnen")),
        (("the teachers"), ("die Lehrerinnen")),
        (("the professor"), ("der Professorin")),
        (("the teacher"), ("der Lehrer")),
        (("the students"), ("die Studenten")),
        (("the student"), ("der Schüler")),
        (("the student"), ("der Studentin")),
        (("the cooks"), ("die Köche")),
        (("the doctors"), ("die Ärzte")),
        (("the job"), ("die Beruf")),
        (("the doctor"), ("der Ärztin")),
    ]
}
duolingo_set_58 = {
    'name' : 'Duolingo Set 58',
    'words' : [
        (("the jobs"), ("die Berufe")),
        (("the doctor"), ("der Arzt")),
        (("the cook"), ("der Koch")),
        (("v. acts"), ("handelt")),
        (("v. be"), ("sei")),
        (("v. go"), ("gehe")),
        (("v. act"), ("handle")),
        (("v. take"), ("nimm")),
        (("v. drink"), ("trink")),
        (("the buses"), ("die Busse")),
        (("colorful"), ("buntes")),
        (("gray"), ("grauen")),
        (("tan"), ("braune")),
        (("green"), ("grünes")),
        (("green"), ("grünen")),
        (("white"), ("weißes")),
        (("white"), ("weiße")),
        (("the red"), ("das Rot")),
        (("red"), ("rote")),
        (("green"), ("grüne")),
        (("red"), ("roter")),
        (("red"), ("rotes")),
        (("blueness"), ("blaue")),
        (("blue"), ("blauen")),
        (("redden"), ("roten")),
        (("black"), ("schwarze")),
        (("black"), ("schwarzes")),
        (("the colours"), ("die Farben")),
        (("the colour"), ("die Farbe")),
        (("the billions"), ("die Milliarden")),
    ]
}
duolingo_set_59 = {
    'name' : 'Duolingo Set 59',
    'words' : [
        (("the billion"), ("die Milliarde")),
        (("the millions"), ("die Millionen")),
        (("the million"), ("die Million")),
        (("the liter"), ("der Liter")),
        (("the percent"), ("das Prozent")),
        (("the percent"), ("das Prozente")),
        (("the meter"), ("der Meter")),
        (("v. bay"), ("bucht")),
        (("the trip"), ("die Tour")),
        (("the route"), ("die Strecke")),
        (("the cars"), ("die Autos")),
        (("v. wander"), ("wandere")),
        (("the vacation"), ("der Urlaub")),
        (("the train"), ("der Zug")),
        (("v. beech"), ("buche")),
        (("v. flies"), ("fliegt")),
        (("the touring"), ("die Touren")),
        (("the adventure"), ("das Abenteuer")),
        (("v. wanders"), ("wandert")),
        (("the motorcycle"), ("das Motorrad")),
        (("the sightseeing"), ("die Sehenswürdigkeit")),
        (("the flights"), ("die Flüge")),
        (("the travel guide"), ("reiseführer Reiseführer")),
        (("the to travel"), ("das Reisen")),
        (("the passport"), ("der Pass")),
        (("the bus"), ("der Bus")),
        (("the bicycle"), ("das Fahrrad")),
        (("the delay"), ("die Verspätung")),
        (("the ferry"), ("die Fähre")),
        (("the bus stop"), ("die Bushaltestelle")),
    ]
}
duolingo_set_60 = {
    'name' : 'Duolingo Set 60',
    'words' : [
        (("the sweden"), ("die Schweden")),
        (("the visit"), ("der Besuch")),
        (("the ferries"), ("die Fähren")),
        (("v. book"), ("buchen")),
        (("v. hike"), ("wandern")),
        (("italy"), ("italien")),
        (("great britain"), ("großbritannien")),
        (("the boat"), ("das Boot")),
        (("the train"), ("der Bahn")),
        (("the boats"), ("die Boote")),
        (("the stretch"), ("die Strecken")),
        (("the motorcycles"), ("die Motorräder")),
        (("the journey"), ("die Fahrt")),
        (("the rental car"), ("der Mietwagen")),
        (("switzerland"), ("schweiz")),
        (("the swiss"), ("die Schweizer")),
        (("the traffic"), ("der Verkehr")),
        (("the map"), ("die Stadtplan")),
        (("the flight"), ("der Flug")),
        (("the taxi"), ("das Taxi")),
        (("the tourism"), ("der Tourismus")),
        (("the ways"), ("die Wege")),
        (("the landmarks"), ("die Sehenswürdigkeiten")),
        (("spain"), ("spanien")),
        (("the path"), ("der Weg")),
        (("the passports"), ("die Pässe")),
        (("africa"), ("afrika")),
        (("the visa"), ("das Visa")),
        (("the visa"), ("das Visum")),
        (("france"), ("frankreich")),
    ]
}
duolingo_set_61 = {
    'name' : 'Duolingo Set 61',
    'words' : [
        (("hamburg"), ("hamburg")),
        (("the vacation"), ("der Ferien")),
        (("the inch"), ("der Zoll")),
        (("the travel"), ("die Reise")),
        (("the trains"), ("die Züge")),
        (("the cycles"), ("die Fahrräder")),
        (("austria"), ("österreich")),
        (("vienna"), ("wien")),
        (("the automobile"), ("das Auto")),
        (("the fork"), ("die Gabel")),
        (("the dessert"), ("das Nachtisch")),
        (("the supermarket"), ("der Supermarkt")),
        (("the supermarkets"), ("die Supermärkte")),
        (("the customers"), ("die Kundinnen")),
        (("the stores"), ("die Läden")),
        (("the pharmacies"), ("die Apotheken")),
        (("the special offer"), ("das Sonderangebot")),
        (("the coupons"), ("die Gutscheine")),
        (("the pharmacy"), ("die Apotheke")),
        (("the shopping mall"), ("das Einkaufszentrum")),
        (("the bags"), ("die Tüten")),
        (("v. sell"), ("verkaufe")),
        (("v. sold"), ("verkauft")),
        (("the bag"), ("die Tüte")),
        (("the shopping venture"), ("das Einkaufswagen")),
        (("the cashbox"), ("die Kasse")),
        (("v. to sell"), ("verkaufen")),
        (("the load"), ("die Laden")),
        (("the business"), ("das Geschäft")),
        (("the marketplace"), ("der Marktplatz")),
    ]
}
duolingo_set_62 = {
    'name' : 'Duolingo Set 62',
    'words' : [
        (("the bakery"), ("die Bäckerei")),
        (("the neck"), ("der Hals")),
        (("the move"), ("die Rücken")),
        (("the shoulders"), ("die Schultern")),
        (("the necks"), ("die Hälse")),
        (("the mouths"), ("die Münder")),
        (("the poor"), ("die Arme")),
        (("the hands"), ("die Hände")),
        (("the hair"), ("die Haar")),
        (("the eyes"), ("die Augen")),
        (("the faces"), ("die Gesichter")),
        (("the skin"), ("die Haut")),
        (("the blood"), ("das Blut")),
        (("the feet"), ("die Füße")),
        (("the face"), ("das Gesicht")),
        (("the leg"), ("das Bein")),
        (("the foot"), ("der Fuß")),
        (("the legs"), ("die Beine")),
        (("the stomachs"), ("die Mägen")),
        (("the heart"), ("das Herz")),
        (("the chest"), ("die Brust")),
        (("the hearts"), ("die Herzen")),
        (("the stomach"), ("der Magen")),
        (("the breasts"), ("die Brüste")),
        (("the shoulder"), ("die Schulter")),
        (("the tooth"), ("der Zahn")),
        (("the mouth"), ("der Mund")),
        (("v. press"), ("drücke")),
        (("v. presses"), ("drückt")),
        (("the finger"), ("der Finger")),
    ]
}
duolingo_set_63 = {
    'name' : 'Duolingo Set 63',
    'words' : [
        (("the hand"), ("die Hand")),
        (("the head"), ("der Kopf")),
        (("the ear"), ("das Ohr")),
        (("the noses"), ("die Nasen")),
        (("the hair"), ("die Haare")),
        (("the eye"), ("das Auge")),
        (("the body"), ("der Körper")),
        (("the heads"), ("die Köpfe")),
        (("the menu cards"), ("die Speisekarten")),
        (("the twin"), ("der Zwilling")),
        (("the great-grandchildren"), ("die Urenkel")),
        (("the half sisters"), ("die Halbschwestern")),
        (("the weddings"), ("die Hochzeiten")),
        (("the half-brothers"), ("die Halbbrüder")),
        (("the half brother"), ("der Halbbruder")),
        (("the wedding"), ("die Hochzeit")),
        (("the partnerships"), ("die Partnerschaften")),
        (("the partnership"), ("die Partnerschaft")),
        (("the half sister"), ("die Halbschwester")),
        (("the great grandmother"), ("die Urgroßmutter")),
        (("the cousins"), ("die Cousinen")),
        (("the twins"), ("die Zwillinge")),
        (("the cousins"), ("die Cousins")),
        (("the cousin"), ("der Cousine")),
        (("the relatives"), ("die Verwandten")),
        (("the uncle"), ("der Onkel")),
        (("the not"), ("das Nichten")),
        (("the aunts"), ("die Tanten")),
        (("the nephew"), ("der Neffen")),
        (("the relative"), ("der Verwandte")),
    ]
}
duolingo_set_64 = {
    'name' : 'Duolingo Set 64',
    'words' : [
        (("the sun"), ("die Sonne")),
        (("your"), ("deinem")),
        (("her"), ("ihrem")),
        (("v. follows"), ("folgt")),
        (("this"), ("diesem")),
        (("which one"), ("welchem")),
        (("many"), ("vielen")),
        (("this"), ("dieser")),
        (("both"), ("beiden")),
        (("his"), ("seinem")),
        (("our"), ("unserem")),
        (("his"), ("seinen")),
        (("our"), ("unseren")),
        (("v. consequences"), ("folgen")),
        (("his"), ("seiner")),
        (("our"), ("unserer")),
        (("v. episode"), ("folge")),
        (("v. belong"), ("gehören")),
        (("v. to thank"), ("danken")),
        (("v. thanks"), ("danke")),
        (("v. help"), ("helft")),
        (("v. helps"), ("hilft")),
        (("v. belongs"), ("gehört")),
        (("the tip"), ("das Trinkgeld")),
        (("the cents"), ("die Cents")),
        (("the buzz"), ("das Summen")),
        (("the numbers"), ("die Nummern")),
        (("the phone numbers"), ("die Telefonnummern")),
        (("v. buy"), ("kaufe")),
        (("v. win"), ("gewinne")),
    ]
}
duolingo_set_65 = {
    'name' : 'Duolingo Set 65',
    'words' : [
        (("v. wins"), ("gewinnt")),
        (("the dollars"), ("die Dollars")),
        (("v. transfer"), ("überweise")),
        (("v. owns"), ("besitzt")),
        (("the dollar"), ("der Dollar")),
        (("the euro"), ("der Euro")),
        (("v. buys"), ("kauft")),
        (("v. to buy"), ("kaufen")),
        (("the euros"), ("die Euros")),
        (("the money"), ("das Geld")),
        (("the cent"), ("der Cent")),
        (("the prices"), ("die Preise")),
        (("the price"), ("der Preis")),
        (("v. costs"), ("kostet")),
        (("the castles"), ("die Schlösser")),
        (("the bridges"), ("die Brücken")),
        (("the banks"), ("die Banken")),
        (("the benches"), ("die Bänke")),
        (("the bank"), ("die Bank")),
        (("v. say"), ("sagen")),
        (("v. legend"), ("sage")),
        (("v. says"), ("sagt")),
        (("v. show"), ("zeige")),
        (("v. shows"), ("zeigt")),
        (("v. demonstrate"), ("zeigen")),
        (("v. reply"), ("antworten")),
        (("v. answers"), ("antwortet")),
        (("the mushrooms"), ("die Pilze")),
        (("v. have breakfast"), ("frühstücke")),
        (("the nuts"), ("die Nüsse")),
    ]
}
duolingo_set_66 = {
    'name' : 'Duolingo Set 66',
    'words' : [
        (("the forks"), ("die Gabeln")),
        (("the spoon"), ("der Löffel")),
        (("the cake"), ("der Kuchen")),
        (("the dinner"), ("das Abendessen")),
        (("the onions"), ("die Zwiebeln")),
        (("the garlic"), ("der Knoblauch")),
        (("the starter"), ("der Vorspeise")),
        (("the mustard"), ("der Senf")),
        (("the main dish"), ("das Hauptgericht")),
        (("the beans"), ("die Bohnen")),
        (("v. cook"), ("kochen")),
        (("v. cooks"), ("kocht")),
        (("the mushroom"), ("der Pilz")),
        (("the chicken"), ("das Hähnchen")),
        (("the tomato"), ("die Tomate")),
        (("the having lunch"), ("das Mittagessen")),
        (("the recipe"), ("das Rezept")),
        (("the butter"), ("die Butter")),
        (("the jam"), ("die Marmelade")),
        (("the honey"), ("der Honig")),
        (("v. breakfast"), ("frühstückt")),
        (("the cereal"), ("das Müsli")),
        (("the breakfast"), ("das Frühstück")),
        (("the nut"), ("die Nuss")),
        (("the total"), ("die Summe")),
        (("v. counts"), ("zählt")),
        (("the half"), ("die Hälfte")),
        (("the number"), ("die Zahl")),
        (("the phone number"), ("die Telefonnummer")),
        (("the numbers"), ("die Zahlen")),
    ]
}
duolingo_set_67 = {
    'name' : 'Duolingo Set 67',
    'words' : [
        (("the number"), ("die Nummer")),
        (("along"), ("entlang")),
        (("their"), ("ihren")),
        (("your"), ("ihre")),
        (("the corners"), ("die Ecken")),
        (("the streets"), ("die Straßen")),
        (("the granddaughters"), ("die Enkelinnen")),
        (("the grandmothers"), ("die Großmütter")),
        (("the grandfathers"), ("die Großväter")),
        (("the relationships"), ("die Beziehungen")),
        (("the familys"), ("die Familien")),
        (("the mothers"), ("die Müttern")),
        (("the father"), ("der Vater")),
        (("the mother"), ("die Mutter")),
        (("the mothers"), ("die Mütter")),
        (("the grannies"), ("die Omas")),
        (("the grandpas"), ("die Opas")),
        (("the granny"), ("die Oma")),
        (("the grandpa"), ("der Opa")),
        (("the grandfather"), ("der Großvater")),
        (("the grandmother"), ("die Großmutter")),
        (("the grandson"), ("der Enkel")),
        (("the granddaughter"), ("die Enkelin")),
        (("the relationship"), ("die Beziehung")),
        (("the family"), ("die Familie")),
        (("the partner"), ("der Partner")),
        (("the brothers and sisters"), ("die Geschwister")),
        (("the daughter"), ("die Tochter")),
        (("the daughters"), ("die Töchter")),
        (("the fathers"), ("die Väter")),
    ]
}
duolingo_set_68 = {
    'name' : 'Duolingo Set 68',
    'words' : [
        (("the sons"), ("die Söhne")),
        (("the brothers"), ("die Brüder")),
        (("the sisters"), ("die Schwestern")),
        (("the brothers"), ("die Bruder")),
        (("the sister"), ("die Schwester")),
        (("the son"), ("der Sohn")),
        (("which"), ("welche")),
        (("whom"), ("wen")),
        (("whose"), ("wessen")),
        (("the reply"), ("die Antworten")),
        (("whom"), ("wem")),
        (("who"), ("wer")),
        (("the answer"), ("die Antwort")),
        (("the question"), ("die Frage")),
        (("what"), ("was")),
        (("the ask"), ("die Fragen")),
        (("the gender"), ("das Geschlechter")),
        (("the groups"), ("die Gruppen")),
        (("the lady"), ("die Dame")),
        (("the people"), ("die Personen")),
        (("the girlfriends"), ("die Freundinnen")),
        (("the neighbours"), ("die Nachbarn")),
        (("the enemies"), ("die Feinde")),
        (("the fan"), ("der Fan")),
        (("the neighbor"), ("der Nachbar")),
        (("the member"), ("das Mitglied")),
        (("the members"), ("die Mitglieder")),
        (("the beginner"), ("der Anfänger")),
        (("the fans"), ("die Fans")),
        (("the visitor"), ("der Besucher")),
    ]
}
duolingo_set_69 = {
    'name' : 'Duolingo Set 69',
    'words' : [
        (("the group"), ("die Gruppe")),
        (("the audience"), ("die Publikum")),
        (("the guests"), ("die Gäste")),
        (("the guest"), ("der Gast")),
        (("the opponent"), ("der Gegner")),
        (("the gender"), ("das Geschlecht")),
        (("the turk"), ("der Türke")),
        (("the mr"), ("der Herr")),
        (("the adults"), ("die Erwachsene")),
        (("the men's"), ("die Herren")),
        (("the ladies"), ("die Damen")),
        (("the citizen"), ("der Bürger")),
        (("the surname"), ("der Name")),
        (("the person"), ("die Person")),
        (("the first name"), ("der Vornamen")),
        (("the first name"), ("der Vorname")),
        (("the friends"), ("die Freunde")),
        (("the names"), ("die Namen")),
        (("the infant"), ("das Baby")),
        (("the girlfriend"), ("die Freundin")),
        (("the friend"), ("der Freund")),
        (("the babies"), ("die Babys")),
        (("the sofas"), ("die Sofas")),
        (("the lamps"), ("die Lampen")),
        (("the lights"), ("die Lichter")),
        (("the chairs"), ("die Stühlen")),
        (("the cabinets"), ("die Schränke")),
        (("the chairs"), ("die Stühle")),
        (("the balconies"), ("die Balkone")),
        (("the cover"), ("die Decken")),
    ]
}
duolingo_set_70 = {
    'name' : 'Duolingo Set 70',
    'words' : [
        (("the lamp"), ("die Lampe")),
        (("the beds"), ("die Betten")),
        (("the socket"), ("die Steckdose")),
        (("the bed"), ("das Bett")),
        (("the carpets"), ("die Teppiche")),
        (("the carpet"), ("der Teppich")),
        (("the sockets"), ("die Steckdosen")),
        (("the light"), ("das Licht")),
        (("the tables"), ("die Tische")),
        (("the cabinet"), ("das Schrank")),
        (("the table"), ("der Tisch")),
        (("the sofa"), ("das Sofa")),
        (("the living room"), ("das Wohnzimmer")),
        (("the chair"), ("der Stuhl")),
        (("the furniture"), ("die Möbel")),
        (("the kitchens"), ("die Küchen")),
        (("the balcony"), ("der Balkon")),
        (("the apartments"), ("die Wohnungen")),
        (("the flat"), ("die Wohnung")),
        (("the top, roof"), ("die Dach")),
        (("the basement, cellar"), ("der Keller")),
        (("the roofs"), ("die Dächer")),
        (("the key"), ("der Schlüssel")),
        (("the kitchen"), ("die Küche")),
        (("the stairway"), ("die Treppe")),
        (("the doors"), ("die Türen")),
        (("the fences"), ("die Zäune")),
        (("the fence"), ("der Zaun")),
        (("the stairs"), ("die Treppen")),
        (("v. opens"), ("öffnet")),
    ]
}
duolingo_set_71 = {
    'name' : 'Duolingo Set 71',
    'words' : [
        (("v. open"), ("öffne")),
        (("the door"), ("die Tür")),
        (("the ceiling"), ("die Decke")),
        (("the walls"), ("die Wände")),
        (("the window"), ("das Fenster")),
        (("v. to open"), ("öffnen")),
        (("mine"), ("meines")),
        (("all"), ("alle")),
        (("other"), ("anderen")),
        (("each"), ("jede")),
        (("be"), ("sein")),
        (("this"), ("diesen")),
        (("your"), ("eure")),
        (("his"), ("seine")),
        (("the tool"), ("das Werkzeug")),
        (("the vehicle"), ("das Fahrzeug")),
        (("the building"), ("das Gebäude")),
        (("the bridge"), ("die Brücke")),
        (("the park"), ("der Park")),
        (("the room"), ("der Zimmer")),
        (("the school"), ("die Schule")),
        (("the houses"), ("die Häuser")),
        (("the markets"), ("die Märkte")),
        (("the village"), ("das Dorf")),
        (("the parks"), ("die Parks")),
        (("the country"), ("das Land")),
        (("the city"), ("die Stadt")),
        (("v. to build"), ("bauen")),
        (("the villages"), ("die Dörfer")),
        (("the cities"), ("die Städte")),
    ]
}
duolingo_set_72 = {
    'name' : 'Duolingo Set 72',
    'words' : [
        (("the hotels"), ("die Hotels")),
        (("the street"), ("die Straße")),
        (("the lock"), ("das Schloss")),
        (("the libraries"), ("die Bibliotheken")),
        (("the restaurant"), ("das Restaurant")),
        (("the train stations"), ("die Bahnhöfe")),
        (("the railway station"), ("der Bahnhof")),
        (("the library"), ("die Bibliothek")),
        (("the hotel"), ("das Hotel")),
        (("the restaurants"), ("die Restaurants")),
        (("the schools"), ("die Schulen")),
        (("the house"), ("das Haus")),
        (("the gardens"), ("die Gärten")),
        (("the garden"), ("der Garten")),
        (("the market"), ("der Markt")),
        (("some"), ("manche")),
        (("everyone"), ("jeder")),
        (("lots"), ("viele")),
        (("this"), ("dieses")),
        (("these"), ("diese")),
        (("both"), ("beide")),
        (("this"), ("dies")),
        (("the bananas"), ("die Bananen")),
        (("yours"), ("eurer")),
        (("our"), ("unser")),
        (("your"), ("euer")),
        (("our"), ("unsere")),
        (("the mountain"), ("der Berg")),
        (("the earth"), ("die Erde")),
        (("the stars"), ("die Sterne")),
    ]
}
duolingo_set_73 = {
    'name' : 'Duolingo Set 73',
    'words' : [
        (("the sky"), ("der Himmel")),
        (("v. falls"), ("fällt")),
        (("the star"), ("der Stern")),
        (("v. fall"), ("fallen")),
        (("v. live"), ("lebe")),
        (("the sea"), ("das Meer")),
        (("the flower"), ("die Blume")),
        (("the moon"), ("der Mond")),
        (("the flowers"), ("die Blumen")),
        (("the fire"), ("das Feuer")),
        (("the mountains"), ("die Berge")),
        (("the wind"), ("der Wind")),
        (("the tree"), ("der Baum")),
        (("the trees"), ("die Bäume")),
        (("the buttons"), ("die Knöpfe")),
        (("the trousers"), ("die Hose")),
        (("the shoes"), ("die Schuhe")),
        (("the coats"), ("die Mäntel")),
        (("the jacket"), ("die Jacke")),
        (("the stud"), ("das Knopf")),
        (("the jewellery"), ("der Schmuck")),
        (("the ring"), ("der Ring")),
        (("the spot"), ("die Fleck")),
        (("the bags"), ("die Taschen")),
        (("the cosmetics"), ("die Kosmetik")),
        (("the rings"), ("die Ringe")),
        (("the stains"), ("die Flecken")),
        (("the bag"), ("die Tasche")),
        (("v. fit"), ("passen")),
        (("the jackets"), ("die Jacken")),
    ]
}
duolingo_set_74 = {
    'name' : 'Duolingo Set 74',
    'words' : [
        (("the dress"), ("das Kleidung")),
        (("the pants"), ("die Hosen")),
        (("the coat"), ("der Mantel")),
        (("the shirt"), ("das Hemd")),
        (("the shoe"), ("der Schuh")),
        (("v. wearing"), ("trägt")),
        (("v. wear"), ("tragen")),
        (("the skirts"), ("die Röcke")),
        (("the dress"), ("das Kleid")),
        (("the skirt"), ("der Rock")),
        (("v. sluggish"), ("trage")),
        (("the clothes"), ("die Kleider")),
        (("the cap"), ("die Hut")),
        (("the hats"), ("die Hüte")),
        (("v. write"), ("schreibe")),
        (("v. games"), ("spiele")),
        (("v. ride"), ("fahre")),
        (("v. moves"), ("fährt")),
        (("v. likes"), ("mögt")),
        (("v. needs"), ("braucht")),
        (("v. paid"), ("bezahlt")),
        (("v. brings"), ("bringt")),
        (("v. bring"), ("bringen")),
        (("v. run"), ("rennen")),
        (("v. knows"), ("kennt")),
        (("v. journey"), ("fahrt")),
        (("v. writes"), ("schreibt")),
        (("v. hears"), ("hört")),
        (("v. sleep"), ("schlafen")),
        (("v. power"), ("macht")),
    ]
}
duolingo_set_75 = {
    'name' : 'Duolingo Set 75',
    'words' : [
        (("v. pay"), ("bezahlen")),
        (("v. enough"), ("reicht")),
        (("v. begin"), ("beginne")),
        (("v. to wash"), ("waschen")),
        (("v. washes"), ("wäscht")),
        (("v. need"), ("brauchen")),
        (("v. begins"), ("beginnt")),
        (("v. runs"), ("rennt")),
        (("v. thinks"), ("denkt")),
        (("v. drive"), ("fahren")),
        (("v. swims"), ("schwimmt")),
        (("v. sees"), ("sieht")),
        (("v. to like"), ("mögen")),
        (("v. learns"), ("lernt")),
        (("v. learn"), ("lerne")),
        (("v. running"), ("läuft")),
        (("v. make"), ("mache")),
        (("v. to run"), ("laufen")),
        (("v. want"), ("will")),
        (("v. plays"), ("spielt")),
        (("v. goes"), ("geht")),
        (("v. play"), ("spielen")),
        (("the beetle"), ("der Käfer")),
        (("the strawberries"), ("die Erdbeeren")),
        (("the to fly"), ("das Fliegen")),
        (("the insects"), ("die Insekten")),
        (("the pigs"), ("die Schweine")),
        (("the oil"), ("das Öl")),
        (("v. understand"), ("verstehen")),
        (("v. understands"), ("versteht")),
    ]
}
duolingo_set_76 = {
    'name' : 'Duolingo Set 76',
    'words' : [
        (("v. speak"), ("spreche")),
        (("v. speaks"), ("spricht")),
        (("germany"), ("deutschland")),
        (("v. come"), ("komme")),
        (("v. comes"), ("kommt")),
        (("karl"), ("karl")),
        (("julia"), ("julia")),
        (("v. name is"), ("heiße")),
        (("v. is called"), ("heißt")),
        (("v. reading"), ("lese")),
        (("the apple"), ("der Apfel")),
    ]
}

duolingo_sets = [
    duolingo_set_0,
    duolingo_set_1,
    duolingo_set_2,
    duolingo_set_3,
    duolingo_set_4,
    duolingo_set_5,
    duolingo_set_6,
    duolingo_set_7,
    duolingo_set_8,
    duolingo_set_9,
    duolingo_set_10,
    duolingo_set_11,
    duolingo_set_12,
    duolingo_set_13,
    duolingo_set_14,
    duolingo_set_15,
    duolingo_set_16,
    duolingo_set_17,
    duolingo_set_18,
    duolingo_set_19,
    duolingo_set_20,
    duolingo_set_21,
    duolingo_set_22,
    duolingo_set_23,
    duolingo_set_24,
    duolingo_set_25,
    duolingo_set_26,
    duolingo_set_27,
    duolingo_set_28,
    duolingo_set_29,
    duolingo_set_30,
    duolingo_set_31,
    duolingo_set_32,
    duolingo_set_33,
    duolingo_set_34,
    duolingo_set_35,
    duolingo_set_36,
    duolingo_set_37,
    duolingo_set_38,
    duolingo_set_39,
    duolingo_set_40,
    duolingo_set_41,
    duolingo_set_42,
    duolingo_set_43,
    duolingo_set_44,
    duolingo_set_45,
    duolingo_set_46,
    duolingo_set_47,
    duolingo_set_48,
    duolingo_set_49,
    duolingo_set_50,
    duolingo_set_51,
    duolingo_set_52,
    duolingo_set_53,
    duolingo_set_54,
    duolingo_set_55,
    duolingo_set_56,
    duolingo_set_57,
    duolingo_set_58,
    duolingo_set_59,
    duolingo_set_60,
    duolingo_set_61,
    duolingo_set_62,
    duolingo_set_63,
    duolingo_set_64,
    duolingo_set_65,
    duolingo_set_66,
    duolingo_set_67,
    duolingo_set_68,
    duolingo_set_69,
    duolingo_set_70,
    duolingo_set_71,
    duolingo_set_72,
    duolingo_set_73,
    duolingo_set_74,
    duolingo_set_75,
    duolingo_set_76,
]
